### PR TITLE
LPS-167614 Omit ul li if there is only one link in quick access nav

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-167614

### CODE REVIEW

**Review by ethib137 — APPROVED** [review]
LGTM. Thanks @pat270 !

**Comment by ethib137** [comment]
@eltonccdantas yes please analyze the failures. thanks

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:reevaluate:1267401_9786

**Comment by eltonccdantas** [comment]
I'm taking a look at it 🕵🏻

**Comment by eltonccdantas** [comment]
Hey @pat270 and @ethib137, the failures seem unrelated 🎉 , may I forward it?

[Comparison Run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2348186602&testrayRunIdA=2347769989&statusB=3)

[testray-results](https://github.com/liferay-peds/liferay-portal/files/11735013/testray-results.csv)

**Comment by eltonccdantas** [comment]
ci:forward

**Comment by john-co** [comment]
ci:forward:force

**Comment by eltonccdantas** [comment]
Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/136328

**Pull request closed without merging**
