### PR TITLE
LPS-194951 Added menu role to selection field type.

### PR DESCRIPTION
**Pull request by ilzamcmed**
Original PR: https://github.com/liferay-peds/liferay-portal/pull/232

### CODE REVIEW

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
LGTM!! 

I think test fails are not related but sometimes POSI test could make focus in an element with a tabindex="0". we should do it only of the item is interactive

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
> LGTM!!
> 
> I think test fails are not related but sometimes POSI test could make focus in an element with a tabindex="0". we should do it only of the item is interactive

Nice, @marcoscv-work ... I've just triggered `ci:test:relevant` again because the other two tries we had, the tests did not even run.

**Comment by ilzamcmed** [comment]
ci:stop

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
Hey @ilzamcmed, the failures are unrelated to your pull request 🎉 
[
comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1693846193223&testrayRunIdA=2418030551&testrayRunIdB=2418327193)

**Comment by eltonccdantas** [comment]
ci:forward:force

**Pull request closed without merging**
