### PR TITLE
LPS-168408

### PR DESCRIPTION
**Pull request by marcoscv-work**
- Added a more recommended "Skip to Main Content" visual design (removing interface flickering, etc)
- Add styles to style-theme in order to make skip to content more configurable in themes for customers
- Add the word "main" to the text "Skip to Main Content" in order to be more specific

image

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:sf

**Review by veroglez — APPROVED** [review]

**Comment by veroglez** [comment]
ci:forward

**Comment by marcoscv-work** [comment]
ci:forward

**Comment by eltonccdantas** [comment]
Hey @marcoscv-work, I've analyzed your pull request. Although there are unique failures on `BlogsEntry#CannotExecuteXSSInContent` and `BlogsEntry#ExternalVideoEmbeddedInBlogContentFieldCanBePlayed`, they seem to be unrelated to your PR. 

error message:
`java.lang.Exception: Invalid URL: http://cloud-10-0-12-62.lax.liferay.com:8080/web/guest/Blogs Page/-/blogs/Blogs Entry Title Build info: version: '4.7.2', revision: '4d4020c3b7' System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.138-rancher', java.version: '1.8.0_121' Driver info: driver.version: unknown /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/BlogsNavigator.macro[openToBlogEntry]:242 /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/collaboration/blogs/BlogsEntry.testcase[ExternalVideoEmbeddedInBlogContentFieldCanBePlayed]`
and
`java.lang.Exception: process hasn't exited /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/headless/portalinstance/HeadlessPortalInstanceAPI.macro[addPortalInstance]:63 /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/SignIn.macro[signInPortalInstanceSetUp]:68 /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/TestCase.macro[setUpPortalInstance]:217 /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/collaboration/blogs/BlogsEntry.testcase[set-up]`

What do you think?


[Comparison Run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2314958764&testrayRunIdA=2314137643&statusB=3)

[testray-results](https://github.com/liferay-peds/liferay-portal/files/11531396/testray-results.csv)

[VLOOKUP with tests that failed in both (comparison run and testray script)](https://docs.google.com/spreadsheets/d/1CAwXp6Fd5dggGpN5WTXIsBEJOkqX_-GH/edit?usp=sharing&ouid=101533607319431228990&rtpof=true&sd=true)

**Comment by marcoscv-work** [comment]
Thanks!
Can we sent it directly to Bryan then?

**Comment by eltonccdantas** [comment]
> Thanks! Can we sent it directly to Bryan then?

You may manually forward it if no other dev review is needed.

**Pull request closed without merging**
