### PR TITLE
LPS-178869 Add context to last column of search container headers

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Review by marcoscv-work — APPROVED** [review]

**Comment by marcoscv-work** [comment]
LGTM!

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Review by marcoscv-work — APPROVED** [review]

**Comment by andreluis2022** [comment]
ci:help

**Comment by andreluis2022** [comment]
ci:bundle

**Comment by andreluis2022** [comment]
Hey @veroglez, I looked into the errors and they don't seem to be related to your PR according to this [comparison](url). You can manually forward if no further developer review is needed.

CC/@mateusralv LGTM!

**Comment by ealonso** [comment]
ci:forward:force

**Comment by veroglez** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/133804

**Pull request closed without merging**
