### PR TITLE
LPS-183977 Create accessibility ci test suite

### PR DESCRIPTION
**Pull request by john-co**
**Description**
Create a ci test suite that runs all available accessibility tests.

**Test Plan**
- [x] running the test suite runs all poshi/functional tests that have `portal.accessibility = "true"`

**JIRA TICKET**
https://issues.liferay.com/browse/LPS-183977

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:accessibility-all:nocompile

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
@ethib137 I'll go ahead and forward this tomorrow if no other comments from the team.

**Comment by ethib137** [comment]
@john-co looks good. One minor thing, would it maybe be more consistent naming to simply call the test suite `accessibility` rather than `accessibility-all`?

**Comment by john-co** [comment]
> One minor thing, would it maybe be more consistent naming to simply call the test suite accessibility rather than accessibility-all?

I was thinking about this too. The reason why I added `-all` was because if I add any trailing modifiers to the command (ie: `ci:test:accessibilty:nocompile`), then github automatically transforms accessibility to an emoji ( ci:test:accessibilty:nocompile ).  The command will still work functionally but visually bothered me. Thinking about it again today, it probably is a small thing that won't happen too often. I'll change it back to `accessibility` so we can be consistent in the naming with the other test suites. Thanks!

**Comment by ethib137** [comment]
Haha... thanks for sharing that! 😂 What emoji did it try to add? You've got to enjoy those little quirks. 😉

**Comment by john-co** [comment]
:accessibility: :smile:

**Comment by john-co** [comment]
ci:test:accessibility

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
