### PR TITLE
LPS-168793 HR_499 SR should read the three-dot icon of segments item as "More Option Button"

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Screen reader should read the three-dot icon of segments item as "More Option Button"
[Link to story or ticket](https://issues.liferay.com/browse/LPS-168793)

Proposed Solution
========
We have added a message to the `<liferay-ui:icon-menu>` indicating the goal of the icon.

Steps to Verify:
----------------

1. Use JAWS
2. Navigate to Product menu > People > Segments
3. Navigate to an item's three-dot icon of table and assert the SR announces

### CODE REVIEW

**Comment by marcoscv-work** [comment]
@veroglez

**Comment by veroglez** [comment]
Reviewing it!

**Comment by veroglez** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
