### PR TITLE
LPS-169105 HRG_31 Links should identify with color and underline or chevron and color

### PR DESCRIPTION
**Pull request by veroglez**
It fixes https://issues.liferay.com/browse/LPS-169105

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
@pat270 could you review the styles of this PR? Thanks in advance! 😄

**Comment by marcoscv-work** [comment]
LGTM! Thank you for fixing much more than the issue indicates!

We can go ahead!

**Comment by marcoscv-work** [comment]
ci:forward

**Comment by veroglez** [comment]
ci:forward

**Comment by mateusralv** [comment]
I'm on it 🕵🏽

**Comment by mateusralv** [comment]
Hi @veroglez the failures are not related to your PR.

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1678881844425&testrayRunIdA=2230714778&testrayRunIdB=2230910311)

**Comment by veroglez** [comment]
Thanks to check it @mateusralv! 😄

**Comment by veroglez** [comment]
ci:foward

**Comment by veroglez** [comment]
Forwarding manually since failures are not related: https://github.com/brianchandotcom/liferay-portal/pull/131839

(cc @mateusralv)

**Pull request closed without merging**
