### PR TITLE
LPS-198078 - Test Fix for DataSetSettings.testcase

### PR DESCRIPTION
**Pull request by eltonccdantas**
[Ticket](https://liferay.atlassian.net/browse/LPS-198078)

Test Fix for DataSetSettings.testcase

### CODE REVIEW

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:help

**Comment by eltonccdantas** [comment]
ci:test:peds-sm

**Comment by eltonccdantas** [comment]
Hey @john-co, could you please review it and see if you agree with my changes?

It seems to be fixed now.
image

**Comment by john-co** [comment]
Thanks @eltonccdantas , the changes make sense to me. However, this test doesn't belong to PEDS team. It should belong to FI team...please forward the fix to FI team. We need them to adjust the testray components and component name to not use Feature Flags.

**Comment by eltonccdantas** [comment]
> Thanks @eltonccdantas , the changes make sense to me. However, this test doesn't belong to PEDS team. It should belong to FI team...please forward the fix to FI team. We need them to adjust the testray components and component name to not use Feature Flags.

Alrighty.

**Pull request closed without merging**
