### PR TITLE
LPS-190444 fix error when validating focus without any element

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Fixes [LPS-190444](https://liferay.atlassian.net/browse/LPS-190444) and [LPS-190440](https://liferay.atlassian.net/browse/LPS-190440)

The Clay update includes the fix for these two tickets https://github.com/liferay/clay/pull/5632.

**Steps to reproduce:**

1. Navigate to the Page Tree in guest site
2. Type Home in search bar

and

1. Go to the Knowledge base
2. Click the navigation (Templates or Suggestions) in the vertical bar of the side panel

### CODE REVIEW

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
The `:dxp:apps:portal-workflow:portal-workflow-kaleo-designer-web:packageRunTest` test is not related to our changes, I ran it locally without these changes and it still fails.

**Comment by john-co** [comment]
ci:test:stable

**Comment by eltonccdantas** [comment]
ci:test:stable

**Comment by eltonccdantas** [comment]
ci:test:stable

**Comment by eltonccdantas** [comment]
ci:help

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:forward:force

**Comment by eltonccdantas** [comment]
ci:forward:force

**Comment by eltonccdantas** [comment]
ci:forward:force

**Pull request closed without merging**
