### PR TITLE
LPS-186092 Add Autom. Test Accessibility#AssertFileUploadPageIsAccessible 

### PR DESCRIPTION
**Pull request by eltonccdantas**
[Ticket](https://liferay.atlassian.net/browse/LPS-186092)

add poshi test for regression LPS-165394

Given admin page with File Upload
When run axe-core
Then no errors returned

### CODE REVIEW

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:help

**Comment by eltonccdantas** [comment]
ci:test:peds-accessibility

**Comment by eltonccdantas** [comment]
ci:test:peds-accessibility:nocompile

**Review by john-co — CHANGES_REQUESTED** [review]
The test itself looks good. Let's move this to either an existing Lima owned testcase or create one for Lima team, since File Upload is Documents and Media (DM) related and not owned by PEDS.

**Comment by john-co** [comment]
Also, that's really strange that peds-accessibility ran so many tests...it's only supposed to run 3 functional tests and js-unit...

**Comment by eltonccdantas** [comment]
> The test itself looks good. Let's move this to either an existing Lima owned testcase or create one for Lima team, since File Upload is Documents and Media (DM) related and not owned by PEDS.

ic... you mean something like `AccessibilityLima`

**Comment by eltonccdantas** [comment]
Do you plan to work on `Accessibility${team}.testcase` for each team?

**Comment by eltonccdantas** [comment]
> The test itself looks good. Let's move this to either an existing Lima owned testcase or create one for Lima team, since File Upload is Documents and Media (DM) related and not owned by PEDS.

Do you plan to work on Accessibility${team}.testcase for each team?

**Comment by eltonccdantas** [comment]
> Also, that's really strange that peds-accessibility ran so many tests...it's only supposed to run 3 functional tests and js-unit...

Yeah... 🤔

**Comment by john-co** [comment]
Move it to a file called DMDocumentAccessibility.testcase. Same location as other DM testcases.

**Comment by john-co** [comment]
> Do you plan to work on Accessibility${team}.testcase for each team?

I'd like to avoid this direct responsibility to do the action. I would rather have us advise and encourage other teams to do it.

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
