### PR TITLE
LPS-180859 Replace nav-underline by nav-tabs

### PR DESCRIPTION
**Pull request by veroglez**
Fixes https://issues.liferay.com/browse/LPS-180859

### CODE REVIEW

**Comment by veroglez** [comment]
Hi @marcoscv-work, could you take a look this? Thanks in advance!

**Comment by veroglez** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
LGTM!

**Comment by veroglez** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:forward

**Comment by ethib137** [comment]
Looks good @veroglez... Make sure to also check for all instances of `<liferay-ui:tabs` tag being used. Any time it includes the type param it won't be including the `nav-tabs` class.

**Comment by veroglez** [comment]
Hi @ethib137! I have checked all tab cases. I have fixed all cases affected by removing the `nav-underline` class. The rest of the cases that had a param type have not changed.

After a quick review of some cases with param `type="dropdown"`, it looks like they were broken a while ago (see image), this is not related with this PR. We could create a new task to fix these cases.

**Comment by ethib137** [comment]
@veroglez perfect! Sounds all good. No need to create a task for `type="dropdown"`. That should get taken care of by migrating to the new clay tabs taglib and there is already a [ticket](https://issues.liferay.com/browse/LPS-173332) for it. Thanks for looking into that!

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
I'm taking a look 🕵🏽

**Comment by mateusralv** [comment]
ci:test:bundle

**Comment by mateusralv** [comment]
ci:test:bundle

**Comment by marcoscv-work** [comment]
@mateusralv do you think we can go ahead with this PR?

**Comment by mateusralv** [comment]
Hi @veroglez and @marcoscv-work I have sent the fix for the tests that are failing in this PR, I will follow up if the relevant round returns green in my PR https://github.com/liferay-peds/liferay-portal/pull/16

This PR has 91 tests with single failures

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1681234614447&testrayRunIdA=2264382824&testrayRunIdB=2264489725)

**Comment by veroglez** [comment]
see https://github.com/liferay-peds/liferay-portal/pull/16

**Pull request closed without merging**
