### PR TITLE
LPS-187577 - Add  Autom. Test ConfigurationCanBeToggledWithKeyboard

### PR DESCRIPTION
**Pull request by eltonccdantas**
[Ticket](https://liferay.atlassian.net/browse/LPS-187577)

Given Accessibility Menu
When focus on a configuration toggle with keyboard
And toggle a configuration with "Enter" key
Then configuration is toggled

### CODE REVIEW

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:accessibility-menu

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:accessibility-menu

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:accessibility-menu

**Review by john-co — APPROVED** [review]
Looks good to me! :sunglasses:

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
