### PR TITLE
LPS-180859 LPS-180859 Replace nav-underline by nav-tabs + Test fix

### PR DESCRIPTION
**Pull request by mateusralv**
Adding test fix to correct poshi tests that are failing because of PR below

@veroglez  If ci:test:relevant is green could you add https://github.com/liferay-peds/liferay-portal/pull/16/commits/adb98466ea72e112abad495444cc89f63f492ced in PR original and forward? 😄 

Original PR: https://github.com/liferay-peds/liferay-portal/pull/13

---
Fixes https://issues.liferay.com/browse/LPS-180859

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
The number of single fault tests has decreased, it is now 16, tomorrow I will create another test fix for the remaining failures

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2266540592&testrayRunIdA=2266316269&statusB=3)

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
Hi @mateusralv! Thanks for the verification. I think we can go ahead with this PR and send it to Brian.

**Comment by mateusralv** [comment]
Ok, thanks 😄

**Comment by mateusralv** [comment]
ci:forward

**Comment by marcoscv-work** [comment]
@mateusralv thanks for working on this. Can we send the PR to Brian?

**Comment by mateusralv** [comment]
@marcoscv-work yes, the failures are not related!

**Pull request closed without merging**
