### PR TITLE
LPS-198267 Avoid setting style when it is a beta button

### PR DESCRIPTION
**Pull request by veroglez**
Hi guys!

From the Echo team we discovered this issue (https://liferay.atlassian.net/browse/LPS-198267) when adding a Beta button in a panel (with class `.sidebar-sm`). Here I send you the fix, could you review it?

Thank in advance!

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Thanks @veroglez. @pat270 can you review this?

**Comment by pat270** [comment]
@veroglez @ethib137 The `:not(.btn-unstyled)` styles are from https://github.com/liferay/liferay-portal/commit/e7b3d864e89e943f2a8d7280efe4ebdb6a5a2687. The issue is https://liferay.atlassian.net/browse/LPS-101239. I think I will put this pattern into Cadmin since we are using it in all our admin side panels. We will have more control over the btn size selectors if we absorb it there and won't need to keep adding to the `:not` selector as we add more buttons like deprecated.

**Pull request closed without merging**
