### PR TITLE
LPS-195972 Fluid layout should apply to Applications Menu

### PR DESCRIPTION
**Pull request by ethib137**
Resent from: https://github.com/liferay-peds/liferay-portal/pull/258

https://liferay.atlassian.net/browse/LPS-195972

Screenshot 2023-09-22 at 4 06 24 PM

Hey @pat270, based on the conversation in Slack let's move forward without changing the behavior on small screens. The only thing we still need is some basic styling updates for the sites section. I made what I think are the necessary changes in the last commit. Feel free to make any changes you see as necessary.

### CODE REVIEW

**Comment by pat270** [comment]
@ethib137 LGTM!

**Review by pat270 — APPROVED** [review]

**Comment by pat270** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:reevaluate:1327401_2188

**Comment by eltonccdantas** [comment]
Hey @pat270 and @ethib137, the failures are unrelated... May we forward this one or you're still going to modify it?

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1695640069994&testrayRunIdA=2428672771&testrayRunIdB=2429853320)

**Comment by ethib137** [comment]
@eltonccdantas this is good to be forwarded! Thanks!

**Pull request closed without merging**
