### PR TITLE
LPS-168263 Stopping gif animations and some sidebar animations

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
How to test it in MacOS:

https://user-images.githubusercontent.com/7963804/232720409-45491bfb-1034-48f2-aaa6-7476ee158184.mov

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
