### PR TITLE
LPS-197491 Removed tabindex for form field types.

### PR DESCRIPTION
**Pull request by SelenaAungst**
https://liferay.atlassian.net/browse/LPS-197491
Removed based on comment from https://liferay.atlassian.net/browse/LPP-50956

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
LGTM!

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
@SelenaAungst , I'm just double checking but since this looks like it will affect all form builder form inputs, did you make sure to manually test all of them to see that they are focusable and behaving as expected?

**Comment by SelenaAungst** [comment]
Hi @ethib137, 
I tested all of the form field types manually and it just removes focus from their labels, the fields themselves can still be focused. 

There is the exception of the "Select from List" field cannot be focused at all (maybe related to https://github.com/liferay-peds/liferay-portal/pull/238), and the "Rich Text" field editor buttons cannot be reached by tabbing through the page, but both of these things were not from my changes as they also occurred when I tested removing my changes.

**Comment by ethib137** [comment]
Okay @SelenaAungst that sounds okay then. Thanks for explaining. This looks good from my perspective then. We just need to have BPM approve it as well. Can you check with them whether they would prefer a PR to their repo, or just to have someone review it here?

**Comment by SelenaAungst** [comment]
Thanks @ethib137! 
I left a comment on https://liferay.atlassian.net/browse/LPS-197491 to ask where the BPM team wants to review this.

**Comment by SelenaAungst** [comment]
@ethib137 They asked me to send a new PR here: https://github.com/liferay-forms/liferay-portal/pull/2337 so I will close this one.

**Pull request closed without merging**
