### PR TITLE
LPS-190405

### PR DESCRIPTION
**Pull request by SelenaAungst**
https://liferay.atlassian.net/browse/LPS-190405

### CODE REVIEW

**Comment by eltonccdantas** [comment]
Hey @SelenaAungst, the failures are unrelated to your pull request, you may forward it if no other dev review is needed!

[comparison run ](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1690292788823&testrayRunIdA=2391154720&testrayRunIdB=2392072846)

**Comment by SelenaAungst** [comment]
Thank you @eltonccdantas!

**Comment by SelenaAungst** [comment]
ci:forward

**Comment by SelenaAungst** [comment]
ci:forward:force

**Pull request closed without merging**
