### PR TITLE
LPS-187704 - Guest config does not persist for first time login

### PR DESCRIPTION
**Pull request by ethib137**
https://issues.liferay.com/browse/LPS-187704

We were checking if `sessionClicksValue !== null`. This was evaluating to true because sessionClicks when unset is equal to undefined. This is a bit hard to keep track of because localStorage values return null when they are unset. Rather than hope that in the future we will remember which one has which unset value, it seems simpler to have a function to check if null or undefined since in our case both would mean the value is unset.

### CODE REVIEW

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
:heavy_check_mark: **Passed Manual testing** 

Issue described in https://issues.liferay.com/browse/LPS-187704 is no longer reproducible and light manual exploratory testing found no regressions.

Ok to forward from QA perspective. Pending dev reviewer approval.

**Review by matuzalemsteles — APPROVED** [review]
Makes sense to me. Another option would be to change the conditional operator to not compare the values and use the `!=` operator to convert the operand types before the comparison, so even if `sessionClicksValue` is `null` or `undefined` it will enter conditional. But I think not many people know this so it can be confusing in the long run maybe it's safer to go with the function to be explicit.

**Comment by ethib137** [comment]
Yeah, I think the function is much less likely to be accidentally changed in the future because of someone being unaware of the context. Thanks.

**Comment by ethib137** [comment]
ci:forward

**Pull request closed without merging**
