### PR TITLE
LPS-182764 FeatureFlagStatus should be renamed to FeatureFlagType

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-182764](https://issues.liferay.com/browse/LPS-182764).

@ethib137

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:reevaluate:1387401_7430

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
No related failures @drewbrokke @ethib137

**Comment by ethib137** [comment]
LGTM

**Comment by ethib137** [comment]
ci:forward:force

**Comment by ethib137** [comment]
ci:forward:force

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:forward:force

**Pull request closed without merging**
