### PR TITLE
LPS-198690 - Apply --control-menu-container-height css variable to PeDs Components

### PR DESCRIPTION
**Pull request by pat270**
https://liferay.atlassian.net/browse/LPS-198690
https://liferay.atlassian.net/browse/LPS-198686
https://liferay.atlassian.net/browse/LPS-198684

> This PR is consistently applying the use of the --control-menu-container-height css variable to handle the offset for elements that have a fixed position.

New pull with SF fix.

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
@eltonccdantas I fixed the SF issue here.

**Comment by pat270** [comment]
This LGTM!

**Comment by pat270** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:forward

**Pull request closed without merging**
