### PR TITLE
LPS-197126 - Include utility classes to match FDS styling.

### PR DESCRIPTION
**Pull request by ethib137**
https://liferay.atlassian.net/browse/LPS-197126

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
Is it needed to run any other suite?

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
@ethib137 Is this what we expect? I thought the initial idea was to make the FDS match the style of the Lexicon and I wouldn't agree. From what I remember this also seems to be something brought over from Clay rather than Lexicon if I'm not mistaken it was inherited from bootstrap so I'm not sure if this is expected.

**Comment by ethib137** [comment]
My expectation was that we were only moving to use the Clay Table markup so that it improves the accessibility, not that we were trying to completely change how FDS looked. I also thought the current FDS styling is closer to what we will be moving to with [nested roles](https://liferay.atlassian.net/wiki/spaces/PEDS/pages/2432237790/Nested+Rows+-+Front-end+DataSet). But, it doesn't really matter that much right now. I expect we will keep the feature flag until we've completed nested rows, so by that time we will have adjusted the styling anyway. I'll go ahead and close this and discard the ticket. 👍🏻

**Pull request closed without merging**
