### PR TITLE
LPS-188275 - Rename label from "Show Underline Effect in Links" to "Underlined Links".

### PR DESCRIPTION
**Pull request by ethib137**
https://liferay.atlassian.net/browse/LPS-188275

Updates label from "Show Underline Effect in Links" to "Underlined Links" and makes a few other renames in the code for consistency.

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Ok to forward from QA perspective. Pending dev approval.

**Comment by john-co** [comment]
The functional smoke test failures look like they fail inconsistently and randomly based on test history.

**Comment by ethib137** [comment]
ci:forward:force

**Pull request closed without merging**
