### PR TITLE
LPS-187706 Enable a visibilityControllerKey attribute for configuration interface methods

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-187706](https://issues.liferay.com/browse/LPS-187706).

Hey @ethib137, this change is only for the updates to `configuration-admin-web` that deals with allowing the `visibilityControllerKey` on individual method attributes. It does not include the update to `feature-flag-web` that needs to be audited by the performance team, those will be sent separately under [LPS-171225](https://liferay.atlassian.net/browse/LPS-171225).

### CODE REVIEW

**Review by ethib137 — APPROVED** [review]
LGTM. Thanks @drewbrokke

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:reevaluate:1327401_703

**Comment by eltonccdantas** [comment]
ci:forward:force

**Comment by eltonccdantas** [comment]
ci:reevaluate:1317401_8649

**Comment by eltonccdantas** [comment]
ci:test:stable

**Comment by eltonccdantas** [comment]
ci:forward:force

**Pull request closed without merging**
