### PR TITLE
LPS-196845 - Fix sidebar tabs styles

### PR DESCRIPTION
**Pull request by marcoscv-work**
From:

image

image

To: 

image

image

### CODE REVIEW

**Comment by marcoscv-work** [comment]
Should we redirect this PR to echo?

**Comment by ethib137** [comment]
Hey @marcoscv-work it looks like there is still a light border at the bottom of the active tab. That shouldn't be there, right?

Screenshot 2023-09-22 at 10 37 40 AM

**Comment by marcoscv-work** [comment]
Yeah, I've created this issue:
https://liferay.atlassian.net/browse/LPS-196996

**Comment by marcoscv-work** [comment]
Rebased and resend to echo team

**Pull request closed without merging**
