### PR TITLE
LPS-143585 Adds cadmin css class for portlet configuration

### PR DESCRIPTION
**Pull request by veroglez**
Hi guys!!

In Echo team we are working on adding `cadmin` to the portlet configuration. However, when adding `cadmin`, all CKEditor styles were broken. In this PR, I have added the minimal css so that CKEditor looks correctly by adding `cadmin`. @pat270 @marcoscv-work could you take a look? Only the last two commits (https://github.com/liferay-peds/liferay-portal/pull/70/commits/42dd37d6e5a055f29a85fe24af142d5f9ee679f7, https://github.com/liferay-peds/liferay-portal/pull/70/commits/cfa8ef1006100f440e8626a94ffa7c3ffbb40660) needs to be reviewed, since the rest have been reviewed from Echo.

Here I share some screenshots of:

- Before adding `cadmin`
 ckeditor_before

- After applying `cadmin`
cadmin_and_ckeditor_before

- With the changes applied in this PR
cadmin_and_ckeditor_after

Thanks in advance!

### CODE REVIEW

**Comment by eltonccdantas** [comment]
Hey @veroglez, I've analyzed your pull request, and the only failure related to it is concerning `LookAndFeel#ConfigureLookAndFeelOfWidget`,
That's weird because it also failed on my master locally, I intend to continue the analysis Tomorrow, is that ok for you?

[comparison  run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2323559646&testrayRunIdA=2323205149&statusB=3)

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
A lot of work here adding CKeditor and CodeMirror styles:

image

It looks great, LGTM!

**Comment by eltonccdantas** [comment]
ci:stop:relevant

**Comment by eltonccdantas** [comment]
Tell me when you're ready and want me to analyze it again 😄

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward:force

**Comment by eltonccdantas** [comment]
I've reviewed the failures and they're actually unrelated. 🎉

**Comment by veroglez** [comment]
Forwarding manually since failures are not related https://github.com/brianchandotcom/liferay-portal/pull/135661

**Pull request closed without merging**
