### PR TITLE
LPS-188077 - Fix for InstanceSettings#ViewPasswordChangedNotificationTemplateUpdated

### PR DESCRIPTION
**Pull request by eltonccdantas**
This PR aims at fixing InstanceSettings#ViewPasswordChangedNotificationTemplateUpdated and other tests by updating the attribute from " Enter Again " to "Reenter Password"

[Ticket](https://liferay.atlassian.net/browse/LPS-188077)

### CODE REVIEW

**Comment by eltonccdantas** [comment]
ci:stop:relevant

**Comment by eltonccdantas** [comment]
ci:help

**Comment by eltonccdantas** [comment]
ci:relevant

**Comment by eltonccdantas** [comment]
ci:stop:relevant

**Comment by eltonccdantas** [comment]
ci:stop:forward

**Comment by eltonccdantas** [comment]
ci:stop:relevant

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:stop:relevant

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:peds-sm

**Comment by eltonccdantas** [comment]
ci:stop:relevant

**Comment by eltonccdantas** [comment]
ci:relevant

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:bundle

**Pull request closed without merging**
