### PR TITLE
LPS-188743 - Site Settings Accessibility Menu sometimes traps keyboard and mouse actions after opening the modal

### PR DESCRIPTION
**Pull request by ethib137**
https://liferay.atlassian.net/browse/LPS-188743

Due to Senna, we need to detach the openAccessibilityMenu event before SPA navigation to avoid opening the menu multiple times.

### CODE REVIEW

**Review by matuzalemsteles — APPROVED** [review]
@ethib137 makes sense. Another option here would be to make the menu accessibility script `permanent` so that during navigation, Senna doesn't have to rerun the menu script every time it browses.

**Comment by ethib137** [comment]
Hey @matuzalemsteles I briefly looked into making it permanent, but I wasn't sure how to do that since we are using the React taglib to instantiate the component and not controlling our own script. Do you know if there is a way to make that work in this situation?

**Comment by matuzalemsteles** [comment]
> I briefly looked into making it permanent, but I wasn't sure how to do that since we are using the React taglib to instantiate the component and not controlling our own script. Do you know if there is a way to make that work in this situation?

Oh yeah, I'm not sure if that's possible. Maybe @izaera can help us here.

**Comment by izaera** [comment]
At the moment there's no way to customize the `<script>` tag attributes because you would need to pass them through, at least these 5 layers:

1. https://github.com/liferay/liferay-portal/blob/0c9f52de7a10307fb825fbdf0f371aba4cc247a1/modules/apps/portal-template/portal-template-react-renderer-api/src/main/java/com/liferay/portal/template/react/renderer/ComponentDescriptor.java
2. https://github.com/liferay/liferay-portal/blob/05c7bf71d4ed4785944103c383b3ee7d6251d271/modules/apps/portal-template/portal-template-react-renderer-impl/src/main/java/com/liferay/portal/template/react/renderer/internal/ReactRendererUtil.java
3. https://github.com/liferay/liferay-portal/blob/9f8945fdb7024ece8f71d0eb82097928c9c5ac0b/portal-kernel/src/com/liferay/portal/kernel/servlet/taglib/aui/ScriptData.java
4. https://github.com/liferay/liferay-portal/blob/e574b7ab3fd68412be2b3d01afb5b1017e87c2c1/portal-kernel/src/com/liferay/portal/kernel/servlet/taglib/aui/JSFragment.java
5. https://github.com/liferay/liferay-portal/blob/991bee3d633c18bc104554fd7ae2e04b358415b0/modules/apps/frontend-js/frontend-js-web/src/main/java/com/liferay/frontend/js/web/internal/servlet/taglib/aui/PortletDataRendererImpl.java

Then, even if you passed the attributes through, there's not a 1:1 relationship between React components and `<script>` tags, since `ScriptData` is in fact designed to coalesce several code fragments into as few `<script>` tags as possible.

So, I would say you can't do that, but if there's no other way to achieve what you want, we may need to provide another FI API or hack something around `ReactRendererUtil` at your side of the code. In any case, this deserves its own LPS if we go this route to, at least, do an spike and see the possible options.

**Comment by ethib137** [comment]
ci:reevaluate:1327401_715

**Comment by ethib137** [comment]
Thanks @eltonccdantas . Yes please analyze it.

**Comment by eltonccdantas** [comment]
The failures are unrelated to it... 🎉  

[comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1689164102226&testrayRunIdA=2377781881&testrayRunIdB=2376978255)

**Comment by eltonccdantas** [comment]
ci:forward:force

**Pull request closed without merging**
