### PR TITLE
LPS-196641 Create a FeatureFlagListener SPI

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-196641](https://issues.liferay.com/browse/LPS-196641).

FYI @shuyangzhou

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/liferay-peds/liferay-portal/pull/287

**Comment by shuyangzhou** [comment]
ci:stop

**Comment by shuyangzhou** [comment]
ci:close

**Comment by drewbrokke** [comment]
See https://github.com/liferay-peds/liferay-portal/pull/294

**Pull request closed without merging**
