### PR TITLE
LPS-187122 Overlapping in Custom CSS configuration in the page editor

### PR DESCRIPTION
**Pull request by veroglez**
Fixes https://issues.liferay.com/browse/LPS-187122

Hi guys!!

In the Echo team we have this issue https://issues.liferay.com/browse/LPS-187122 related to the custom css editor in the page editor. The problem is that the styles that were added here https://github.com/liferay-peds/liferay-portal/pull/70/commits/2341d4d93908fe78b95106296a999e12c4d87e7f were not isolated from ckeditor. So in this PR, I have isolated the codemirror styles from ckeditor and I have added some more that were needed. @marcoscv-work @pat270 could you take a look? Only this commit need review bd5fbaaf3cf44a5ab314aacfb1f78728301b7858

Here I share some screenshots of:

- Before adding cadmin
without_cadmin

- After applying cadmin
with_cadmin

- With the changes applied in this PR
fix_styles

Thanks in advance!

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
It looks good to me!

**Comment by marcoscv-work** [comment]
ci:forward

**Pull request closed without merging**
