### PR TITLE
LPS-187586 | Add Autom. Test ShowUnderlineEffectsCanApplyUnderlineClassToLinksImmediately

### PR DESCRIPTION
**Pull request by eltonccdantas**
[Ticket](https://liferay.atlassian.net/browse/LPS-187586)

Given home page
And underline class not applied to Powered by Liferay
// verify show underline config in accessibility menu is off
// verify link element "Powered by Liferay" does not have "c-prefers-link-underline" class present
When access Accessibility Menu
And toggle ON show underline effect in links 
Then Powered by Liferay link has underline class applied
// assert link element "Powered by Liferay" has "c-prefers-link-underline" class present

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:accessibility-menu:nocompile

**Comment by john-co** [comment]
ci:forward

**Comment by eltonccdantas** [comment]
ci:forward:force

**Pull request closed without merging**
