### PR TITLE
LPS-196641 Create a FeatureFlagListener SPI

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-196641](https://issues.liferay.com/browse/LPS-196641).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Comment by eltonccdantas** [comment]
🕵🏻

**Comment by eltonccdantas** [comment]
I'm not sure about it... let's try another round.

[comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1695990130069&testrayRunIdA=2433035916&testrayRunIdB=2433801629)

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Sounds good to me, thanks @eltonccdantas !

**Comment by eltonccdantas** [comment]
ci:forward:force

**Pull request closed without merging**
