### PR TITLE
LPS-189455 Add text-underline class

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
Hey @veroglez, the [failures look unrelated](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1688493826478&testrayRunIdA=2369774879&testrayRunIdB=2370199534) to your PR 🎉

**Comment by eltonccdantas** [comment]
Is any other dev review still needed?

**Comment by marcoscv-work** [comment]
LGTM!

**Comment by marcoscv-work** [comment]
ci:forward

**Comment by eltonccdantas** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
ci:forward

**Comment by veroglez** [comment]
Forwarded manually to https://github.com/brianchandotcom/liferay-portal/pull/137470

**Pull request closed without merging**
