### PR TITLE
LPS-199154 Replace static service tracker with Snapshot in FeatureFlagManagerUtil

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-199154](https://issues.liferay.com/browse/LPS-199154).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
🕵🏻

**Comment by eltonccdantas** [comment]
Hey @drewbrokke , due to the amount of tests labeled `testRun: Failed to run test on CI`, it is safer to trigger relevant again and analyze the new results.

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2441266156&testrayRunIdA=2440865274&statusB=3)

**Comment by eltonccdantas** [comment]
Hey @drewbrokke, it seems the failures are unrelated to your changes.

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1697548478478&testrayRunIdA=2442197218&testrayRunIdB=2441982390)

**Comment by ethib137** [comment]
ci:forward:force

**Pull request closed without merging**
