### PR TITLE
LPS-196013 Set color for taglib-icon-help

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://liferay.atlassian.net/browse/LPS-196013 

Expected result for `liferay-ui:icon-help` icon
LPS-196013

I made it work in most cases but not in the permission's modal. There is a style coming from Clay that I don't know how can be override. Could you please review it? 

```
.table-title[href]:hover,
.table-title [href]:hover {
  color: #212529;
}
```
Thank you very much!

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ethib137** [comment]
Thanks @ambrinchaudhary 

@pat270 is this something we could fix directly in Clay?

**Comment by eltonccdantas** [comment]
ci:test:clay

**Comment by eltonccdantas** [comment]
ci:stop

**Comment by eltonccdantas** [comment]
ci:stop:clay

**Comment by eltonccdantas** [comment]
Since it adds lines to a `scss` file, should we trigger any suite?

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by pat270** [comment]
@ethib137 We won't be able to fix this in Clay until we replace `liferay-ui:icon-help`, update the markup to match Clay, or just add this to Clay. The markup currently looks like:

```html
<span class="ml-1 taglib-icon-help lfr-portal-tooltip" tabindex="0" title="...">
  <span class="c-inner" tabindex="-1" id="acnq">
    <svg aria-hidden="true" class="lexicon-icon lexicon-icon-question-circle-full" focusable="false">
      ...
    </svg>
  </span>
  <span class="taglib-text hide-accessible sr-only">...</span>
</span>
```

**Comment by ambrinchaudhary** [comment]
Thank you a lot @pat270! I see you already sent the fix for the permission issue (❤️ ), so I guess I don't need to override the `[href]` styel here and this pull is ready to forward, am I right?

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1407401_6334

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1407401_6334

**Comment by eltonccdantas** [comment]
Hey @ethib137 and @ambrinchaudhary, after reaching out to @pat270 in our stand-up meeting this afternoon, he said this could be forwarded.

**Comment by eltonccdantas** [comment]
ci:forward:force

**Pull request closed without merging**
