### PR TITLE
LPS-185489 Update packages `@clayui/*` to v3.96.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**
### Bug Fixes

-   **@clayui/autocomplete:** fix error when rendering two collections ([03473be](https://github.com/liferay/clay/commit/03473be98f22d52613b741528cbebec64073b771))
-   **@clayui/multi-select:** fix error when not doing OOTB filter ([0da49e2](https://github.com/liferay/clay/commit/0da49e22a0483350af87ba417a6c9d1826add723))

### Bug Fixes

-   **@clayui/autocomplete:** don't open menu if items is null ([300fb73](https://github.com/liferay/clay/commit/300fb73452613c588d613e8d9cc687faaab99b68))
-   **@clayui/core:** fixes bug with not having a focusable item when there is no active item ([f852f26](https://github.com/liferay/clay/commit/f852f26244eabf7464a285b2aa2d72bba14f4853))
-   **@clayui/drop-down:** fix error when breaking component when group has no items ([b13f32c](https://github.com/liferay/clay/commit/b13f32c72fce7b88abefca02d5ab9ca7efc7fa81))

### Features

-   **@clayui/autocomplete:** adds new API to customize input ([b6a213b](https://github.com/liferay/clay/commit/b6a213b325e82d2472977463e76762252a519fe6))
-   **@clayui/card:** moves root `aria-label` to card titles ([6dc08c2](https://github.com/liferay/clay/commit/6dc08c219c2df8a37ce0bf414724348e2fe0003d))
-   **@clayui/core:** add backward compatibility for VerticalNav ([bc1c59c](https://github.com/liferay/clay/commit/bc1c59ceadda34d9519806a5840c02b56ea58297))
-   **@clayui/core:** adds new `active` API to VerticalNav ([ebec342](https://github.com/liferay/clay/commit/ebec342f3f9b79abf86f25ab12f00754ee3952fa))
-   **@clayui/multi-select:** adds implementation of new autocomplete ([506c72f](https://github.com/liferay/clay/commit/506c72f4bcfa4beaec74d09bbf2fc0d58577cd35))

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
Hey @matuzalemsteles , it seems SF is failing due to this:
`[exec] checkTypeScriptTypeArtifacts() failed: Error: Type generation was successful but 1 project was out of date. Please commit updated versions of the artifacts in the projects listed above.
     [exec] 
     [exec] Prettier checked 1 file
     [exec] 
     [exec] 1 of 3 jobs failed`

**Comment by matuzalemsteles** [comment]
Thanks @eltonccdantas I'll take a look

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
🕵🏻

**Comment by eltonccdantas** [comment]
Hey @matuzalemsteles, I've analyzed the results from the last relevant run, and the only failures that might be related to your pull request are the ones below:

- Lima Headless | com.liferay.headless.delivery.resource.v1_0.test.StructuredContentFolderResourceTest
- Portal Services | com.liferay.portal.fragment.bundle.watcher.test.PortalFragmentBundleWatcherTest
- Staging | com.liferay.staging.test.StagingDataPortletPreferencesTest

What do you think? Based on my last clay analysis, when [you commented on CI's inconsistencies](https://github.com/liferay-peds/liferay-portal/pull/53#:~:text=Hey%20%40eltonccdantas%20I,sending%20it%20manually.), these integration failures also look unrelated, right?

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2327317822&testrayRunIdA=2324830679&statusB=3)

[testray-results](https://github.com/liferay-peds/liferay-portal/files/11624665/testray-results.5.csv)

[VLOOKUP](https://docs.google.com/spreadsheets/d/1U6nP7lCND9wmODFuzDpJlCaoYVQeX9zh/edit?usp=sharing&ouid=101533607319431228990&rtpof=true&sd=true)

**Comment by john-co** [comment]
ci:test:stable

**Comment by eltonccdantas** [comment]
As the failures seem unrelated, I manually forwarded it to @brianchandotcom, [#135746](https://github.com/brianchandotcom/liferay-portal/pull/135746)

**Comment by john-co** [comment]
Hi @matuzalemsteles, can you check the [js unit error](https://testray.liferay.com/home/-/testray/case_results/2328154440?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2328150049%26testrayRunId%3D2328154387%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)? It may be related to the changes.

[Full jenkins log](https://testray.liferay.com/reports/production/logs/2023-06/test-1-38/test-portal-acceptance-pullrequest(master)/7802/js-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

Error Snippet:
```
     [exec] > Task :dxp:apps:portal-search-tuning:portal-search-tuning-rankings-web:packageRunTest FAILED
     [exec] FAIL test/js/components/ResultRankingsForm.es.js (28.929s)
     [exec]   ��� ResultRankingsForm ��� renders blank alias
     [exec] 
     [exec]     expect(received).toBe(expected) // Object.is equality
     [exec] 
     [exec]     Expected: " "
     [exec]     Received: ""
     [exec] 
     [exec]       110 | 			});
     [exec]       111 | 
     [exec]     > 112 | 			expect(input.getAttribute('value')).toBe(expectedValue);
     [exec]           | 			                                    ^
     [exec]       113 | 
     [exec]       114 | 			const tagsElement = container.querySelectorAll(
     [exec]       115 | 				'.label-item-expand'
     [exec] 
     [exec]       at test/js/components/ResultRankingsForm.es.js:112:40
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec] Test Suites: 1 failed, 16 passed, 17 total
     [exec] Tests:       1 failed, 2 skipped, 118 passed, 121 total
     [exec] Snapshots:   0 total
     [exec] Time:        30.831s
     [exec] Ran all test suites.
     ```

**Comment by matuzalemsteles** [comment]
I sent a fix for testing, it looks good now.

**Comment by eltonccdantas** [comment]
Thanks for reviewing @john-co

**Comment by eltonccdantas** [comment]
ci:test:stable

**Comment by eltonccdantas** [comment]
ci:forward:force

**Comment by john-co** [comment]
looks unrelated, we should manually forward it since it's stuck on `ci:test:stable`

**Comment by eltonccdantas** [comment]
Manually sent to @brianchandotcom, [#135793](https://github.com/brianchandotcom/liferay-portal/pull/135793)

**Comment by matuzalemsteles** [comment]
Reopen again, Brian reverted the change because a Workflow unit test of the instance tracker was failing, further investigation the test is not related to the Clay changes because it is not using any Clay components just an external lib and it seems to be a flaky test, this test it has failed other times but when we run it on CI sometimes it passes, I think the test needs to be rewritten by the team for now I am ignoring the test to avoid failures.

cc @eltonccdantas I will run the tests again.

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
Hey @matuzalemsteles, it seems there's an issue related to [semantic versioning](https://github.com/liferay-peds/liferay-portal/pull/72#:~:text=%5Becho%5D%20Semantic%20versioning%20is%20incorrect.%0A%20%20%20%20%20%20%5Bget%5D%20Getting%3A%20%5C%24%5C%7Bdependencies.url%5C%7D/archive/test%2D1%2D34/test%2Dportal%2Dacceptance%2Dpullrequest%2Ddownstream(master)/519275consoleText%0A%20%20%20%20%20%20%5Bget%5D%20To%3A%20/opt/dev/projects/github/liferay%2Dportal/20230605232550288.txt)

**Comment by eltonccdantas** [comment]
🕵🏻

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:stable

**Comment by eltonccdantas** [comment]
Stable passed, after my comment, it removed the label "passed" to "failed" 🤔

**Comment by eltonccdantas** [comment]
`com.liferay.portal.workflow.kaleo.internal.runtime.integration.test.WorkflowInstanceManagerImplTest ` is not related as you [can see here](https://gist.github.com/eltonccdantas/2b840b1aef51b6d9a02324a4b6029cc9)

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
Hey @matuzalemsteles, I intend to continue the analysis Tomorrow due to the end of my working time Today.

**Comment by eltonccdantas** [comment]
ci:test:workflow

**Comment by eltonccdantas** [comment]
ci:test:workflow-metrics

**Comment by eltonccdantas** [comment]
ci:forward:force

**Comment by eltonccdantas** [comment]
Hey @matuzalemsteles, after analyzing it again with @john-co, we ended up on the same page that the failures are unrelated to your pull request, on every run we have a different error, concerning functional tests, they are clean, I tested other integration tests as well... So we decided to forward it.

**Comment by eltonccdantas** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/136050

**Pull request closed without merging**
