### PR TITLE
LPS-193009 adds ClayTable markup to FDS

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Ticket [LPS-193009](https://liferay.atlassian.net/browse/LPS-193009)

The new look is only activated via the feature flag. We will likely need to update existing FDS tests or other tests when we need to remove the feature flag.

```
feature.flag.LPS-193005=true
```

| New look |
|--------|
| Screenshot 2023-08-29 at 19 22 22 |

### CODE REVIEW

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:help

**Comment by john-co** [comment]
ci:test:frontend-data-set

**Comment by eltonccdantas** [comment]
Due to the amount of `Aborted prior to running test` we've got, I'll trigger `ci:test:frontend-data-set` again

**Comment by eltonccdantas** [comment]
ci:test:frontend-data-set

**Comment by eltonccdantas** [comment]
Hey @matuzalemsteles, it seems your changes affected some paths... I'll work on a fix for them 🕵🏻

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:frontend-data-set

**Comment by matuzalemsteles** [comment]
ci:test:frontend-data-set

**Comment by eltonccdantas** [comment]
ci:reevaluate:1257401_3048

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:frontend-data-set

**Comment by eltonccdantas** [comment]
Hey @matuzalemsteles, I'll analyze the failures as soon as I start work tomorrow morning.

**Comment by eltonccdantas** [comment]
Hey @matuzalemsteles, I do not know what's going on... Although I touched the paths and the tests passed locally, it keeps failing on CI on the same tests... I decided to drop those commits, sync with master and trigger the suites again... 🤞🏻

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:frontend-data-set

**Comment by matuzalemsteles** [comment]
Hey @ethib137 Do you have any idea why this is happening? could it be that the FF is configured incorrectly? For some reason FDS's poshi tests are breaking because it's using the new markup with ClayTable which shouldn't be the case because this is enabled via FF, testing locally the new markup is only visible with FF but it doesn't happen on poshi. I noticed that in other tests poshi is using the current markup instead of the new one, so this is only happening in some test cases.

**Comment by eltonccdantas** [comment]
Hey @matuzalemsteles, I would like to know the expected behavior before working on a fix for those tests... Your changes shouldn't affect the tests, right? 🤔 

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1693949256792&testrayRunIdA=2418745129&testrayRunIdB=2418960536)

**Comment by matuzalemsteles** [comment]
> that looks very odd to me. I don't see any reason why your feature flag wouldn't be working as expected. How can you tell in the test that it is rendering the Clay Table markup?

@ethib137 I'm looking at the poshi report in the failure screenshot, for these tests they are showing, I could be wrong too and this was already the case in these test cases:

- https://testray.liferay.com/reports/production/logs/2023-09/test-1-31/test-portal-acceptance-pullrequest(master)/9321/functional-tomcat90-mysql57-jdk8/0/3/LocalFile.DataSetViewFields_CanChangeCellRenderer/index.html.gz
- https://testray.liferay.com/reports/production/logs/2023-09/test-1-31/test-portal-acceptance-pullrequest(master)/9321/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.DataSetViewFields_CanSelectDropdownOptions/index.html.gz

For these test cases it looks ok:

- https://testray.liferay.com/reports/production/logs/2023-09/test-1-29/test-portal-acceptance-pullrequest(master)/8078/functional-tomcat90-mysql57-chrome100-jdk8/0/16/LocalFile.DataSet_CanSortByName/index.html.gz
- https://testray.liferay.com/reports/production/logs/2023-09/test-1-31/test-portal-acceptance-pullrequest(master)/9321/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.DataSet_AssertTheValueInFieldsName/index.html.gz
- https://testray.liferay.com/reports/production/logs/2023-09/test-1-31/test-portal-acceptance-pullrequest(master)/9321/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.DataSetFragment_CanUseTaxonomyCategorySchema/index.html.gz

> I would like to know the expected behavior before working on a fix for those tests... Your changes shouldn't affect the tests, right? 

@eltonccdantas yes, only if FF is enabled.

**Comment by matuzalemsteles** [comment]
ci:test:frontend-data-set

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:frontend-data-set

**Comment by eltonccdantas** [comment]
Hey @matuzalemsteles, I analyzed the failures on this [comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2421284890&testrayRunIdA=2420185341&statusB=3), I reckon I'll investigate further these tests below just to make sure your changes are not the cause:


[LocalFile.DataSetViewPagination#CanCreatePagination](https://testray.liferay.com/home/-/testray/case_results/2421285101)
[com.liferay.headless.commerce.admin.pricing.resource.v2_0.test.DiscountAccountGroupResourceTest](https://testray.liferay.com/home/-/testray/case_results/2421286933)
[com.liferay.portal.util.test.PortalImplLocalizedFriendlyURLTest](https://testray.liferay.com/home/-/testray/case_results/2421287463)

**Comment by eltonccdantas** [comment]
I ran [com.liferay.headless.commerce.admin.pricing.resource.v2_0.test.DiscountAccountGroupResourceTest](https://testray.liferay.com/home/-/testray/case_results/2421286933) and 
[com.liferay.portal.util.test.PortalImplLocalizedFriendlyURLTest](https://testray.liferay.com/home/-/testray/case_results/2421287463) locally and they passed... 

I'm in doubt about [LocalFile.DataSetViewPagination#CanCreatePagination](https://testray.liferay.com/home/-/testray/case_results/2421285101) now... 🤔

**Comment by eltonccdantas** [comment]
After investigating it with @matuzalemsteles, we could clear the air and assert the failures are unrelated to this pull request 🚀

**Comment by eltonccdantas** [comment]
ci:forward:force

**Comment by eltonccdantas** [comment]
ci:forward:force

**Pull request closed without merging**
