### PR TITLE
LPS-182028 SF

### PR DESCRIPTION
**Pull request by crodriguezy**
Hello team,

first of all I know I should be following the IPT apporoach but this issue came to me before it was officially started.
Second, please let me know if this issue/component does not really belong to you, so I can send it to the correct team.

It tries to solve case described in https://issues.liferay.com/browse/LPS-182028, where notifications from all across the portal include the port information in the URLs informed. I initially reproduced it within email's notifications and did the changes related to it but then I realized it happens also with user notifications (I may be missing something in this PR because there are many)

Could you please have a look to the PR taking into account my comments?
Thanks in advance

### CODE REVIEW

**Comment by crodriguezy** [comment]
Hello @liferay-peds team, did you have the time to have a look at this?
Thank you

**Comment by crodriguezy** [comment]
Hi @ethib137 ,
I'll then open a PTR to the team, because there are cases where https is used but the port is still displayed in notifications URLs. The next notification link:

image

Shows:

https://www.upf.edu:8080/intranet/gestio-del-professorat/inici/-/blogs/269757004

Is it expected?

Thanks

**Comment by ethib137** [comment]
Hi @crodriguezy yes that is still expected. As the link I shared mentions the standard port is 80 for http and 443 for https. So unless they configure it in that way the ports will still be displayed.

**Comment by ethib137** [comment]
@crodriguezy I'm going to close this for now. If we end up deciding this needs a fix we can reopen this then. Thanks.

**Pull request closed without merging**
