### PR TITLE
LPS-180176 Adjust tab styles

### PR DESCRIPTION
**Pull request by veroglez**
It fixed https://issues.liferay.com/browse/LPS-180176

cc @marcoscv-work

### CODE REVIEW

**Comment by marcoscv-work** [comment]
Looks perfect! thanks!

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:forward

**Comment by marcoscv-work** [comment]
ci:forward

**Comment by veroglez** [comment]
ci:stop

**Pull request closed without merging**
