### PR TITLE
LPS-188023 - The "Show Underline Effect in Links" setting should default to FALSE.

### PR DESCRIPTION
**Pull request by ethib137**
https://liferay.atlassian.net/browse/LPS-188023

### CODE REVIEW

**Comment by eltonccdantas** [comment]
I'll take a look at it 🕵🏻

**Comment by eltonccdantas** [comment]
Hey @ethib137, I've analyzed the results and the failures seem to be unrelated to your pull request. May I forward it or will you still work on something?

[testray-results.csv](https://github.com/liferay-peds/liferay-portal/files/11791159/testray-results.4.csv)

**Comment by ethib137** [comment]
ci:forward:force

**Comment by ethib137** [comment]
ci:forward:force

**Comment by eltonccdantas** [comment]
Hey @ethib137, I see that ci:forward:force didn't work.. I'll manually forward it to Brian

**Comment by eltonccdantas** [comment]
It worked 🎉

**Pull request closed without merging**
