### PR TITLE
LPS-196357 Update packages `@clayui/*` to v3.105.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**
### Bug Fixes

-   **@clayui/autocomplete:** fix error when navigating via keyboard with the mouse over the item ([f13e062](https://github.com/liferay/clay/commit/f13e062033445f70df32bdf31d068646215c9a78))
-   **@clayui/css:** Range show clay-range-thumb instead of input range thumb for range with progress ([b5ca9d5](https://github.com/liferay/clay/commit/b5ca9d5c7e8469a165241e64d19565869300066e))
-   **@clayui/css:** Renames form-control-container to input-group-item-focusable ([54b0677](https://github.com/liferay/clay/commit/54b0677bf6eff26c2ab551120ed43a9b0a717100))
-   **@clayui/css:** Use component-focus-box-shadow for anchor tags ([3aaa6a2](https://github.com/liferay/clay/commit/3aaa6a23f94cdf3531c8fc06b607a8c1b98b6427))
-   **@clayui/time-picker:** Removes focus class, no longer needed with focus-within ([059eaf8](https://github.com/liferay/clay/commit/059eaf8d10904f5163e7406fabd2c480a718d0d3))

### Features

-   **@clayui/color-picker:** Add alpha transparency slider ([534ebde](https://github.com/liferay/clay/commit/534ebde9a5b1c3b4e901643682b46d362bb4dd97))
-   **@clayui/color-picker:** Use form-control-container for focus-within ([53df194](https://github.com/liferay/clay/commit/53df1940e153bec42000de0c18ff033b4b6fb401))
-   **@clayui/css:** add new `key` icon ([c2c6851](https://github.com/liferay/clay/commit/c2c68511d765556d6a40fd78889aeaa238c29eea))
-   **@clayui/css:** Adds focus-within ([deeaa3e](https://github.com/liferay/clay/commit/deeaa3ecf863e1fee42c486c7617b2c2d7c4fd6c))
-   **@clayui/css:** Cadmin Clay Color adds hue and alpha range inputs ([b9b9db9](https://github.com/liferay/clay/commit/b9b9db94284c3bd3b91948163eecdd32ae214a0d))
-   **@clayui/css:** Clay Color adds hue and alpha range inputs ([31b74e0](https://github.com/liferay/clay/commit/31b74e01d9fa96cb64e9c67332356d2f741e0f56))
-   **@clayui/css:** Mixins adds clay-range-variant ([350f154](https://github.com/liferay/clay/commit/350f1544a7ae0c7a08319ad3b37f4e01f169ab8b))
-   **@clayui/css:** Mixins clay-form-control-variant adds focus-within ([f359e03](https://github.com/liferay/clay/commit/f359e03dcf72be8e9341662af898c1e5a9924c80))
-   **@clayui/css:** Mixins clay-input-group-item-variant adds focus-within ([ccc74fe](https://github.com/liferay/clay/commit/ccc74fe5f23bab139a83ad42c135b917b472c00e))
-   **@clayui/css:** update `bookmarks` icon and add `bookmarks-full` icon ([db3ff38](https://github.com/liferay/clay/commit/db3ff3899ea974d8b526d66423465542ec51d8f2))
-   **@clayui/css:** update `download`, `import-list`, `import`, `upload-multiple` and `upload` icons ([c8640fd](https://github.com/liferay/clay/commit/c8640fd56d601ab455317bf42f3f8322df490808))
-   **@clayui/date-picker:** Use form-control-container on date-picker input-groups ([32dad5e](https://github.com/liferay/clay/commit/32dad5e6f980d27cb35451a06d9fe47b027a809d))
-   **@clayui/drop-down:** Use form-control-container on search ([5d4c242](https://github.com/liferay/clay/commit/5d4c242da7577800cc067f8d0b61415688ca4d8a))

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:clay

**Comment by john-co** [comment]
**Looks related**
[FormsColorField#PredefinedValueCanBeAdded](https://testray.liferay.com/home/-/testray/case_results/2425813585) hex values changed from lowercase to uppercase, is this intentional?

Possibly related but need to double check next test run to see if same issues occur
- [js unit](https://testray.liferay.com/home/-/testray/case_results/2425814897)

```
     [exec] FAIL test/js/ColorPicker/ColorPicker.es.js
     [exec]   ��� Field Color Picker ��� renders field disabled
     [exec] 
     [exec]     expect(received).toMatchSnapshot()
     [exec] 
     [exec]     Snapshot name: `Field Color Picker renders field disabled 1`
     [exec] 
     [exec]     - Snapshot  - 1
     [exec]     + Received  + 1
     [exec] 
     [exec]     @@ -30,11 +30,11 @@
     [exec]                     type="button"
     [exec]                   />
     [exec]                 </div>
     [exec]               </div>
     [exec]               <div
     [exec]     -           class="input-group-item input-group-append"
     [exec]     +           class="input-group-item input-group-item-focusable input-group-append"
     [exec]               >
     [exec]                 <input
     [exec]                   aria-label="Color selection is 000000"
     [exec]                   class="form-control input-group-inset input-group-inset-before"
     [exec]                   disabled=""
     [exec] 
     [exec]       59 | 		});
     [exec]       60 | 
     [exec]     > 61 | 		expect(container).toMatchSnapshot();
     [exec]          | 		                  ^
     [exec]       62 | 	});
     [exec]       63 | 
     [exec]       64 | 	it('renders field with helptext', () => {
     [exec] 
     [exec]       at Object.<anonymous> (test/js/ColorPicker/ColorPicker.es.js:61:21)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec]   ��� Field Color Picker ��� renders field with helptext
     [exec] 
     [exec]     expect(received).toMatchSnapshot()
     [exec] 
     [exec]     Snapshot name: `Field Color Picker renders field with helptext 1`
     [exec] 
     [exec]     - Snapshot  - 1
     [exec]     + Received  + 1
     [exec] 
     [exec]     @@ -29,11 +29,11 @@
     [exec]                     type="button"
     [exec]                   />
     [exec]                 </div>
     [exec]               </div>
     [exec]               <div
     [exec]     -           class="input-group-item input-group-append"
     [exec]     +           class="input-group-item input-group-item-focusable input-group-append"
     [exec]               >
     [exec]                 <input
     [exec]                   aria-label="Color selection is 000000"
     [exec]                   class="form-control input-group-inset input-group-inset-before"
     [exec]                   type="text"
     [exec] 
     [exec]       75 | 		});
     [exec]       76 | 
     [exec]     > 77 | 		expect(container).toMatchSnapshot();
     [exec]          | 		                  ^
     [exec]       78 | 	});
     [exec]       79 | 
     [exec]       80 | 	it('renders field with label', () => {
     [exec] 
     [exec]       at Object.<anonymous> (test/js/ColorPicker/ColorPicker.es.js:77:21)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec]   ��� Field Color Picker ��� renders field with label
     [exec] 
     [exec]     expect(received).toMatchSnapshot()
     [exec] 
     [exec]     Snapshot name: `Field Color Picker renders field with label 1`
     [exec] 
     [exec]     - Snapshot  - 1
     [exec]     + Received  + 1
     [exec] 
     [exec]     @@ -35,11 +35,11 @@
     [exec]                     type="button"
     [exec]                   />
     [exec]                 </div>
     [exec]               </div>
     [exec]               <div
     [exec]     -           class="input-group-item input-group-append"
     [exec]     +           class="input-group-item input-group-item-focusable input-group-append"
     [exec]               >
     [exec]                 <input
     [exec]                   aria-label="Color selection is 000000"
     [exec]                   class="form-control input-group-inset input-group-inset-before"
     [exec]                   type="text"
     [exec] 
     [exec]       92 | 		});
     [exec]       93 | 
     [exec]     > 94 | 		expect(container).toMatchSnapshot();
     [exec]          | 		                  ^
     [exec]       95 | 	});
     [exec]       96 | 
     [exec]       97 | 	it('renders with basic color', () => {
     [exec] 
     [exec]       at Object.<anonymous> (test/js/ColorPicker/ColorPicker.es.js:94:21)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec]  ��� 3 snapshots failed.
   ``` 
   
   AND
   
   ```
     [exec] > Task :apps:segments:segments-web:packageRunTest
     [exec] PASS test/js/components/criteria_builder/Conjunction.es.js
     [exec]   ��� Console
     [exec] 
     [exec]     console.error ../../../node_modules/warning/warning.js:34
     [exec]       Warning: Button Accessibility: Component has only the Icon declared. Define an `aria-label` or `aria-labelledby` attribute that labels the interactive button that screen readers can read. The `title` attribute is optional but consult your design team.
     [exec]     console.error ../../../node_modules/warning/warning.js:34
     [exec]       Warning: Button Accessibility: Component has only the Icon declared. Define an `aria-label` or `aria-labelledby` attribute that labels the interactive button that screen readers can read. The `title` attribute is optional but consult your design team.
     [exec]     console.error ../../../node_modules/warning/warning.js:34
     [exec]       Warning: Button Accessibility: Component has only the Icon declared. Define an `aria-label` or `aria-labelledby` attribute that labels the interactive button that screen readers can read. The `title` attribute is optional but consult your design team.
     [exec] 
     [exec] PASS test/js/components/inputs/IntegerInput.test.js
     [exec] PASS test/js/components/criteria_sidebar/CriteriaSidebar.test.js
     [exec] PASS test/js/components/criteria_builder/ContributorsBuilder.test.js (5.157s)
     [exec] PASS test/js/components/inputs/DecimalInput.test.js
     [exec] PASS test/js/components/criteria_sidebar/CriteriaSidebarItem.test.js
     [exec] PASS test/js/components/criteria_builder/DropZone.test.js
     [exec] PASS test/js/utils/contributors.es.js
     [exec] PASS test/js/components/criteria_builder/CriteriaRow.test.js (5.509s)
     [exec] PASS test/js/components/segment_edit/SegmentEdit.test.js (5.541s)
     [exec] PASS test/js/components/criteria_builder/CriteriaRowEditable.test.js (5.766s)
     [exec] PASS test/js/components/inputs/BooleanInput.test.js
     [exec] FAIL test/js/components/inputs/DateTimeInput.test.js (6.151s)
     [exec]   ��� DateTimeInput ��� renders type date-time
     [exec] 
     [exec]     expect(received).toMatchSnapshot()
     [exec] 
     [exec]     Snapshot name: `DateTimeInput renders type date-time 1`
     [exec] 
     [exec]     - Snapshot  - 1
     [exec]     + Received  + 1
     [exec] 
     [exec]     @@ -7,11 +7,11 @@
     [exec]           >
     [exec]             <div
     [exec]               class="input-group"
     [exec]             >
     [exec]               <div
     [exec]     -           class="input-group-item"
     [exec]     +           class="input-group-item input-group-item-focusable"
     [exec]               >
     [exec]                 <input
     [exec]                   name="datePicker"
     [exec]                   type="hidden"
     [exec]                   value="2019/01/23"
     [exec] 
     [exec]       33 | 		);
     [exec]       34 | 
     [exec]     > 35 | 		expect(asFragment()).toMatchSnapshot();
     [exec]          | 		                     ^
     [exec]       36 | 
     [exec]       37 | 		const element = getByTestId(DATE_INPUT_TESTID);
     [exec]       38 | 
     [exec] 
     [exec]       at Object.<anonymous> (test/js/components/inputs/DateTimeInput.test.js:35:24)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec]   ��� DateTimeInput ��� renders previous date with wrong date-time
     [exec] 
     [exec]     expect(received).toMatchSnapshot()
     [exec] 
     [exec]     Snapshot name: `DateTimeInput renders previous date with wrong date-time 1`
     [exec] 
     [exec]     - Snapshot  - 1
     [exec]     + Received  + 1
     [exec] 
     [exec]     @@ -7,11 +7,11 @@
     [exec]           >
     [exec]             <div
     [exec]               class="input-group"
     [exec]             >
     [exec]               <div
     [exec]     -           class="input-group-item"
     [exec]     +           class="input-group-item input-group-item-focusable"
     [exec]               >
     [exec]                 <input
     [exec]                   name="datePicker"
     [exec]                   type="hidden"
     [exec]                   value="2019/01/23"
     [exec] 
     [exec]       59 | 		);
     [exec]       60 | 
     [exec]     > 61 | 		expect(asFragment()).toMatchSnapshot();
     [exec]          | 		                     ^
     [exec]       62 | 
     [exec]       63 | 		const element = getByTestId(DATE_INPUT_TESTID);
     [exec]       64 | 
     [exec] 
     [exec]       at Object.<anonymous> (test/js/components/inputs/DateTimeInput.test.js:61:24)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec]   ��� DateTimeInput ��� renders type date
     [exec] 
     [exec]     expect(received).toMatchSnapshot()
     [exec] 
     [exec]     Snapshot name: `DateTimeInput renders type date 1`
     [exec] 
     [exec]     - Snapshot  - 1
     [exec]     + Received  + 1
     [exec] 
     [exec]     @@ -7,11 +7,11 @@
     [exec]           >
     [exec]             <div
     [exec]               class="input-group"
     [exec]             >
     [exec]               <div
     [exec]     -           class="input-group-item"
     [exec]     +           class="input-group-item input-group-item-focusable"
     [exec]               >
     [exec]                 <input
     [exec]                   name="datePicker"
     [exec]                   type="hidden"
     [exec]                   value="2019/01/23"
     [exec] 
     [exec]       85 | 		);
     [exec]       86 | 
     [exec]     > 87 | 		expect(asFragment()).toMatchSnapshot();
     [exec]          | 		                     ^
     [exec]       88 | 
     [exec]       89 | 		const element = getByTestId(DATE_INPUT_TESTID);
     [exec]       90 | 
     [exec] 
     [exec]       at Object.<anonymous> (test/js/components/inputs/DateTimeInput.test.js:87:24)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec]   ��� DateTimeInput ��� renders previous date with wrong date
     [exec] 
     [exec]     expect(received).toMatchSnapshot()
     [exec] 
     [exec]     Snapshot name: `DateTimeInput renders previous date with wrong date 1`
     [exec] 
     [exec]     - Snapshot  - 1
     [exec]     + Received  + 1
     [exec] 
     [exec]     @@ -7,11 +7,11 @@
     [exec]           >
     [exec]             <div
     [exec]               class="input-group"
     [exec]             >
     [exec]               <div
     [exec]     -           class="input-group-item"
     [exec]     +           class="input-group-item input-group-item-focusable"
     [exec]               >
     [exec]                 <input
     [exec]                   name="datePicker"
     [exec]                   type="hidden"
     [exec]                   value="2019/01/23"
     [exec] 
     [exec]       114 | 		);
     [exec]       115 | 
     [exec]     > 116 | 		expect(asFragment()).toMatchSnapshot();
     [exec]           | 		                     ^
     [exec]       117 | 
     [exec]       118 | 		const element = getByTestId(DATE_INPUT_TESTID);
     [exec]       119 | 
     [exec] 
     [exec]       at Object.<anonymous> (test/js/components/inputs/DateTimeInput.test.js:116:24)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec]   ��� DateTimeInput ��� renders date-time with no change in the input
     [exec] 
     [exec]     expect(received).toMatchSnapshot()
     [exec] 
     [exec]     Snapshot name: `DateTimeInput renders date-time with no change in the input 1`
     [exec] 
     [exec]     - Snapshot  - 1
     [exec]     + Received  + 1
     [exec] 
     [exec]     @@ -7,11 +7,11 @@
     [exec]           >
     [exec]             <div
     [exec]               class="input-group"
     [exec]             >
     [exec]               <div
     [exec]     -           class="input-group-item"
     [exec]     +           class="input-group-item input-group-item-focusable"
     [exec]               >
     [exec]                 <input
     [exec]                   name="datePicker"
     [exec]                   type="hidden"
     [exec]                   value="2019/01/23"
     [exec] 
     [exec]       140 | 		);
     [exec]       141 | 
     [exec]     > 142 | 		expect(asFragment()).toMatchSnapshot();
     [exec]           | 		                     ^
     [exec]       143 | 
     [exec]       144 | 		const element = getByTestId(DATE_INPUT_TESTID);
     [exec]       145 | 
     [exec] 
     [exec]       at Object.<anonymous> (test/js/components/inputs/DateTimeInput.test.js:142:24)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec]   ��� DateTimeInput ��� renders date with no change in the input
     [exec] 
     [exec]     expect(received).toMatchSnapshot()
     [exec] 
     [exec]     Snapshot name: `DateTimeInput renders date with no change in the input 1`
     [exec] 
     [exec]     - Snapshot  - 1
     [exec]     + Received  + 1
     [exec] 
     [exec]     @@ -7,11 +7,11 @@
     [exec]           >
     [exec]             <div
     [exec]               class="input-group"
     [exec]             >
     [exec]               <div
     [exec]     -           class="input-group-item"
     [exec]     +           class="input-group-item input-group-item-focusable"
     [exec]               >
     [exec]                 <input
     [exec]                   name="datePicker"
     [exec]                   type="hidden"
     [exec]                   value="2019/01/23"
     [exec] 
     [exec]       167 | 		);
     [exec]       168 | 
     [exec]     > 169 | 		expect(asFragment()).toMatchSnapshot();
     [exec]           | 		                     ^
     [exec]       170 | 
     [exec]       171 | 		const element = getByTestId(DATE_INPUT_TESTID);
     [exec]       172 | 
     [exec] 
     [exec]       at Object.<anonymous> (test/js/components/inputs/DateTimeInput.test.js:169:24)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec]  ��� 6 snapshots failed.
   ```
   

- [modules semantic](https://testray.liferay.com/home/-/testray/case_results/2425817499)

**Comment by john-co** [comment]
[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2424478530&testrayRunIdA=2425808772&statusB=2)

**Comment by john-co** [comment]
ci:test:clay:norebase

**Comment by john-co** [comment]
It does seem like the test batches I previously listed look related to the PR. They still failed in the last test run.

**Comment by matuzalemsteles** [comment]
@john-co thanks, yeah these unit tests I think are related to our change, I'll have to update the tests.

**Comment by matuzalemsteles** [comment]
ci:test:clay

**Comment by john-co** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
Hey @eltonccdantas or @john-co do you think some of these tests are still related.

**Comment by john-co** [comment]
Just started reviewing... :hourglass_flowing_sand:

**Comment by john-co** [comment]
Hi @matuzalemsteles 

These four tests look related to the changes. It affected the hex values and appears to have changed the lowercase letters to uppercase. Is this intentational?

Automated Functional Test | 5 | Forms | Forms | LocalFile.FormsColorField#CanBeDuplicated | 01 |   | FAILED | - | java.lang.Exception: Expected text "ff0d0d" does not match actual text "FF0D0D" at "//div[contains(@data-field-name,'Color')]//div[contains(@class,'color-picker')]//div[contains(@class,'color')]//input[@type='text'] \| //div[@class='ddm-field']//label[text()='Color']/..//input"
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Automated Functional Test | 5 | Forms | Forms | LocalFile.FormsColorField#PredefinedValueCanBeAdded | 01 |   | FAILED | - | java.lang.Exception: Expected text "7f26ff" does not match actual text "7F26FF" at "//div[contains(@data-field-name,'Color')]//div[contains(@class,'color-picker')]//div[contains(@class,'color')]//input[@type='text'] \| //div[@class='ddm-field']//label[text()='Color']/..//input"
Automated Functional Test | 5 | Forms | Forms | LocalFile.FormsEntries#DataIsDisplayedInFieldListFormat | 01 |   | FAILED | - | java.lang.Exception: Element is not present at "//*[contains(@class,'field-list')][contains(.,'5f5f5f')]"
Automated Functional Test | 5 | Forms | Forms | LocalFile.FormsColorField#CanBeSetToRepeatable | 01 |   | FAILED | - | com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//table[contains(.,'Color')]//tbody/tr/td[contains(.,'ff0d0d, FF0D0D')]"

[Automated Functional Test](https://testray.liferay.com/home/-/testray/case_results/2427839593?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	[5](https://testray.liferay.com/home/-/testray/case_results/2427839593?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	[Forms](https://testray.liferay.com/home/-/testray/case_results/2427839593?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	[Forms](https://testray.liferay.com/home/-/testray/case_results/2427839593?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	[LocalFile.FormsColorField#CanBeDuplicated](https://testray.liferay.com/home/-/testray/case_results/2427839593?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	[01](https://testray.liferay.com/home/-/testray/case_results/2427839593?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	
[FAILED](https://testray.liferay.com/home/-/testray/case_results/2427839593?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	-	
java.lang.Exception: Expected text "ff0d0d" does not match actual text "FF0D0D" at "//div[contains(@data-field-name,'Color')]//div[contains(@class,'color-picker')]//div[contains(@class,'color')]//input[@type='text'] | //div[@class='ddm-field']//label[text()='Color']/..//input"
[Automated Functional Test](https://testray.liferay.com/home/-/testray/case_results/2427839457?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	[5](https://testray.liferay.com/home/-/testray/case_results/2427839457?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	[Forms](https://testray.liferay.com/home/-/testray/case_results/2427839457?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	[Forms](https://testray.liferay.com/home/-/testray/case_results/2427839457?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	[LocalFile.FormsColorField#PredefinedValueCanBeAdded](https://testray.liferay.com/home/-/testray/case_results/2427839457?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	[01](https://testray.liferay.com/home/-/testray/case_results/2427839457?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	
[FAILED](https://testray.liferay.com/home/-/testray/case_results/2427839457?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	-	
java.lang.Exception: Expected text "7f26ff" does not match actual text "7F26FF" at "//div[contains(@data-field-name,'Color')]//div[contains(@class,'color-picker')]//div[contains(@class,'color')]//input[@type='text'] | //div[@class='ddm-field']//label[text()='Color']/..//input"
[Automated Functional Test](https://testray.liferay.com/home/-/testray/case_results/2427839523?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	[5](https://testray.liferay.com/home/-/testray/case_results/2427839523?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	[Forms](https://testray.liferay.com/home/-/testray/case_results/2427839523?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	[Forms](https://testray.liferay.com/home/-/testray/case_results/2427839523?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	[LocalFile.FormsEntries#DataIsDisplayedInFieldListFormat](https://testray.liferay.com/home/-/testray/case_results/2427839523?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	[01](https://testray.liferay.com/home/-/testray/case_results/2427839523?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	
[FAILED](https://testray.liferay.com/home/-/testray/case_results/2427839523?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	-	
java.lang.Exception: Element is not present at "//*[contains(@class,'field-list')][contains(.,'5f5f5f')]"
[Automated Functional Test](https://testray.liferay.com/home/-/testray/case_results/2427839452?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	[5](https://testray.liferay.com/home/-/testray/case_results/2427839452?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	[Forms](https://testray.liferay.com/home/-/testray/case_results/2427839452?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	[Forms](https://testray.liferay.com/home/-/testray/case_results/2427839452?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	[LocalFile.FormsColorField#CanBeSetToRepeatable](https://testray.liferay.com/home/-/testray/case_results/2427839452?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	[01](https://testray.liferay.com/home/-/testray/case_results/2427839452?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	
[FAILED](https://testray.liferay.com/home/-/testray/case_results/2427839452?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2427838908%26testrayRunId%3D2427838980%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)	-	
com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//table[contains(.,'Color')]//tbody/tr/td[contains(.,'ff0d0d, FF0D0D')]"

**Comment by matuzalemsteles** [comment]
@john-co Yeah, that's intentional. Can we update these tests?

**Comment by john-co** [comment]
Yea, I can update the tests and will forward.

**Comment by john-co** [comment]
ci:forward:force

**Comment by john-co** [comment]
ci:test:forms

**Comment by john-co** [comment]
pushed to https://github.com/brianchandotcom/liferay-portal/pull/141203

**Pull request closed without merging**
