### PR TITLE
Lps 196641

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @drewbrokke

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
The failures seem to be unrelated. Is any other dev review needed?

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1695817463894&testrayRunIdA=2432169806&testrayRunIdB=2431776582)

**Comment by ethib137** [comment]
LGTM

**Comment by drewbrokke** [comment]
@eltonccdantas I think we're good to go on this one. Thanks!

**Comment by eltonccdantas** [comment]
ci:forward:force

**Comment by drewbrokke** [comment]
@eltonccdantas looks like a merge conflict in this one. I'm going to try to resolve it and send a different pull.

**Comment by eltonccdantas** [comment]
sent [here](https://github.com/liferay-peds/liferay-portal/pull/298)

**Pull request closed without merging**
