### PR TITLE
LPS-192002 Asset Publisher table template should announce column title…

### PR DESCRIPTION
**Pull request by pat270**
… for item actions

https://liferay.atlassian.net/browse/LPP-50337
https://liferay.atlassian.net/browse/LPS-192002

This can be directly backported to 7.3.

/cc @SelenaAungst @pedro-michel 

Edit: PR number
FTSQZtKypegso

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
🕵🏻

**Comment by eltonccdantas** [comment]
We've got a bunch `Failed prior to running test`, so let's run it again just to make sure.

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2396131247&testrayRunIdA=2395783501&statusB=3) 

[testray-results.csv](https://github.com/liferay-peds/liferay-portal/files/12193994/testray-results.3.csv)

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:reevaluate:1277401_9339

**Comment by eltonccdantas** [comment]
Hey @pat270, it seems some of your changes on HTML affected some Xpaths and consequently some tests broke due to that... Would you be able to add me as a contributor to your repository? So I could work on a fix for them.

**Comment by pat270** [comment]
@eltonccdantas I added you as a collaborator

**Comment by liuxingye** [comment]
Hi @pat270 @eltonccdantas 

There is a [flex request](https://liferay.slack.com/archives/CLB4WMEGP/p1690586236723959) for forwarding this since it is `associated to high priority customer issue`. After analyzing the test results of [relevant](https://testray.liferay.com/home/-/testray/case_results?tab=components&testrayBuildId=2396419336), the failures are not related to the pull. Will forward this, thanks.

**Comment by liuxingye** [comment]
ci:forward:force

**Pull request closed without merging**
