### PR TITLE
LPS-195720 Use aria described by to add context to toggle.

### PR DESCRIPTION
**Pull request by SelenaAungst**
https://liferay.atlassian.net/browse/LPS-195720
Resent from https://github.com/liferay-peds/liferay-portal/pull/261

### CODE REVIEW

**Comment by ethib137** [comment]
ci:reevaluate:1297401_8234

**Comment by ethib137** [comment]
@john-co or @eltonccdantas could you check to see if these errors are related to our changes?

**Comment by eltonccdantas** [comment]
Hey, the failures are unrelated, may we forward this one?

[comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1695296923125&testrayRunIdA=2427188346&testrayRunIdB=2428533954) 
[testray-results.csv](https://github.com/liferay-peds/liferay-portal/files/12684194/testray-results.4.csv)

**Comment by ethib137** [comment]
Yes please forward. Thanks @eltonccdantas !

**Comment by eltonccdantas** [comment]
ci:forward:force

**Pull request closed without merging**
