### PR TITLE
LPS-168762 - HR_442 Skip to content link not working on the roles page

### PR DESCRIPTION
**Pull request by ethib137**
https://issues.liferay.com/browse/LPS-168762

The main issues with skip to content take place in the control panel. When in the control panel portlets are in a maximized state so we can move the main content in this scenario to wrap the portlet. This way the control panel is not included inside the main-content section.

The check in max.ftl to see if it is a control panel layout may look a little odd. This is because it's written in velocity even though the template should be freemarker. This is being incorrectly interpreted as a freemarker template so I've created an issue for that here: https://issues.liferay.com/browse/LPS-183098

It's important to only apply this to control panel since the max.ftl template is also used in the full page application template which does not use the admin theme.

This fix will result in skip to main content taking the user directly to the portlet skipping the control panel as seen in the screenshot:
Screenshot 2023-04-27 at 12 15 10 PM

cc: @veroglez @marcoscv-work

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:reevaluate:1377401_10984

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:bundle

**Comment by eltonccdantas** [comment]
ci:test:bundle

**Comment by eltonccdantas** [comment]
Hey @ethib137 , I've analyzed your pull request, and although there are many failures in relevant, only one seems to be related to it:

**The component** :
`Portal Services`

**The case**: 
`com.liferay.portal.osgi.debug.declarative.service.test.DeclarativeServiceDependencyManagerTest`

The error:

```
com.liferay.portal.osgi.debug.declarative.service.test.DeclarativeServiceDependencyManagerTest` > testDeclarativeServiceDependencyManagerResolvedDependencies


	org.junit.ComparisonFailure: expected:<[All declarative service components are satisfied]> but was:<[
	Bundle {id: 1271, name: com.liferay.segments.simulation.web, version: 3.0.29}
		Declarative Service {id: 10850, name: com.liferay.segments.simulation.web.internal.application.list.SegmentsSimulationPanelApp, unsatisfied references: 
			{name: _portlet, target: (javax.portlet.name=com_liferay_segments_simulation_web_internal_portlet_SegmentsSimulationPortlet)}
		}]>
		at org.junit.Assert.assertEquals(Assert.java:117)
		at org.junit.Assert.assertEquals(Assert.java:146)
		at com.liferay.portal.osgi.debug.declarative.service.test.DeclarativeServiceDependencyManagerTest.testDeclarativeServiceDependencyManagerResolvedDependencies(DeclarativeServiceDependencyManagerTest.java:118)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at org.junit.rules.RunRules.evaluate(RunRules.java:20)
		at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
		at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
		at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at org.junit.rules.RunRules.evaluate(RunRules.java:20)
		at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
		at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
		at java.lang.Thread.run(Thread.java:745)
```


[testray-results #28.csv](https://github.com/liferay-peds/liferay-portal/files/11356004/testray-results.28.csv)

[Comparison run #28](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2283967395&testrayRunIdA=2284344904&statusB=3)

[VLOOKUP - Testray vs Comparison #28](https://github.com/liferay-peds/liferay-portal/files/11356059/VLOOKUP.28.xlsx)

**Comment by eltonccdantas** [comment]
I'm afraid I cannot continue the analysis on Monday due to the Holiday in my country, I'll be back on Tuesday, May 2nd.

**Comment by ethib137** [comment]
Hi @eltonccdantas do you have any more updates on this? I'm unsure how the test failure you shared would be related to these changes? Thanks.

**Comment by eltonccdantas** [comment]
> Hi @eltonccdantas do you have any more updates on this? I'm unsure how the test failure you shared would be related to these changes? Thanks.

Let me check it further...

**Comment by eltonccdantas** [comment]
Let's run  `ci:test:relevant` again in order to double-check and be sure it is unrelated, alright?

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
Hey @ethib137 , the failures seem to be unrelated to your pull request. You may manually forward it if no other dev review is needed.

**Comment by ethib137** [comment]
ci:forward:force

**Pull request closed without merging**
