### PR TITLE
LPS-189686 Update packages `@clayui/*` to v3.99.3

### PR DESCRIPTION
**Pull request by matuzalemsteles**
I'm sending more as a draft because this PR will probably fail in CI because we depend on the previous release going into the master, it was just merged into Brian's branch but the master wasn't synced.

---

### Bug Fixes

-   **@clayui/core:** fix collection rendering performance bottleneck ([ecf3155](https://github.com/liferay/clay/commit/ecf315594c07a26bed72aba5f734806e76e56a92))
-   **@clayui/multi-select:** fix loading indicator markup in MultiSelect ([b883824](https://github.com/liferay/clay/commit/b8838247d1638524691fda2a74934e0676e6597d))
-   **@clayui/multi-select:** pass async properties to autocomplete ([0faaab8](https://github.com/liferay/clay/commit/0faaab89049dd9a808666c82b8b8cba455d461f6))
-   **@clayui/multi-select:** stabilize the children reference to avoid unnecessary renderings ([7ff4af5](https://github.com/liferay/clay/commit/7ff4af5ffab85e64220623042e8085a2afd0d565))

### Bug Fixes

-   **@clayui/multi-select:** fix error when not getting list data when pressing enter or comma ([485e0e8](https://github.com/liferay/clay/commit/485e0e8f245c4a366037f3d88f23d48774b2e1dc))

### Bug Fixes

-   **@clayui/autocomplete:** makes new `messages` properties optional ([94eceb6](https://github.com/liferay/clay/commit/94eceb6261334272d0b3a000052a7a9592505284))

### Bug Fixes

-   **@clayui/autocomplete:** adds warning when `filterKey` is not defined and tries to filter an option that is object ([48dd887](https://github.com/liferay/clay/commit/48dd887b7fb6afbade67a98e6d325d1068ddc6b7))
-   **@clayui/autocomplete:** fixes type inference for properties and generic type ([cfc4309](https://github.com/liferay/clay/commit/cfc4309313b46bea777ddae3f9d810ae032b2a3c))
-   **@clayui/core:** fix bug losing component focus when item is removed from DOM ([080b315](https://github.com/liferay/clay/commit/080b31586a9c6fe2c3b3f07ab547be329daa9203))
-   **@clayui/core:** fix error when updating state after component is unmounted ([8a43055](https://github.com/liferay/clay/commit/8a430550f6ff12f19475f4843c6c736a2a5240bb))
-   **@clayui/core:** fix position of TreeView drag preview ([253b784](https://github.com/liferay/clay/commit/253b7846c42c8ebc525605922017ea1d52d8e1d2))
-   **@clayui/core:** fix types for collection with support for string and number ([36cce77](https://github.com/liferay/clay/commit/36cce77a0e962de48148ed24f7c465b67c6cdd36))
-   **@clayui/multi-select:** fixes type inference for properties and generic type ([ae7b2a3](https://github.com/liferay/clay/commit/ae7b2a383de1a710dcfe88e92335ad6afc6613a9))
-   **@clayui/tooltip:** fix error not showing tooltip on nested elements ([cf31736](https://github.com/liferay/clay/commit/cf31736b5515af8c2e906443c86c6cdd4c11631d))

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
I'm on it 🕵🏻 

[testray-results.csv](https://github.com/liferay-peds/liferay-portal/files/12015213/testray-results.1.csv) 

[Comparison runs](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1689081945456&testrayRunIdA=2372452216&testrayRunIdB=2377628573)

**Comment by eltonccdantas** [comment]
The failures seem to be unrelated to your changes 🎉

**Comment by eltonccdantas** [comment]
ci:forward:force

**Pull request closed without merging**
