### PR TITLE
[TS] LPS-185167

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

This is a PR that aims to remove the useless widgets that a deactivated user with a remaining active session.

The approach followed was the one proposed in [PTR-3858](https://issues.liferay.com/browse/PTR-3858), that is, show the error message within the same type of page displayed when the user is configuring her account.

Could you please review it?

Please, let me know if further clarifications are needed for this review or if anyone else should review this PR.

Thanks!

https://issues.liferay.com/browse/LPS-185167

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by john-co** [comment]
ManualTesting

From QA perspective, I would revise the phrase `is not active` to `was deactivated` for better precision on the message. Also would recommend rephrasing the last sentence to something simpler. So something like this:
```
{userfn} {userln}, your account associated with email ${email} was deactivated. To reactivate, please contact your administrator.
```

Also, has it been considered that including the name and email in the same message have any privacy violations for deactivated user? Do we need to mention their name or email is enough?

**Comment by ethib137** [comment]
I added a comment on the associated PTR proposing a different way to fix this issue. This option is being discussed, so we will wait for a decision there before forwarding or closing this PR.

**Comment by ethib137** [comment]
Based on the discussion in the PTR we have decided to take a different approach to fix this. As a result I'm closing this PR. Thanks for the work on this!

**Pull request closed without merging**
