### PR TITLE
LPS-187559 Update packages `@clayui/*` to v3.97.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**
This PR updates the Clay package versions to the latest version that was cut today, it also includes the commits that were reverted from the past release due to the MultiSelect regression that was fixed in this version, it also includes the update in all use cases from DXP that use MultiSelect to use the new APIs.

# Changelog

### Bug Fixes

-   **@clayui/core:** fixes bug with not correctly handling visibility state of arrow buttons ([ff08e9f](https://github.com/liferay/clay/commit/ff08e9fd101c445ba96e39b3b838edf0fb9efbac))
-   **@clayui/css:** Cadmin c-prefers-\* should qualify the cadmin class ([a8b1d7b](https://github.com/liferay/clay/commit/a8b1d7be2f7055bea5430c0783b573f281c7a0b9))
-   **@clayui/css:** Mixins clay-css and transition should output the correct c-prefers-\* selector for cadmin ([b81e2a3](https://github.com/liferay/clay/commit/b81e2a3ab1d029ec7a7dbe8fd6fa1b084281bb52))
-   **@clayui/date-picker:** fixes error when not selecting the year ([747f09e](https://github.com/liferay/clay/commit/747f09e8d3d716eda68d3e080b3efd9592ecf26c))
-   **@clayui/multi-select:** fix error of not showing menu if it has suggestions when menuRenderer is used ([ebc719f](https://github.com/liferay/clay/commit/ebc719ff77ba88dc407d648936cd1edf0e3372e5))

### Features

-   **@clayui/core:** Picker add dropdown-menu-height-lg class to year picker ([c092968](https://github.com/liferay/clay/commit/c09296806d4505cabb47d92ecd5896db795caf41))
-   **@clayui/core:** Picker use dropdown-item-scroll classes ([ec90630](https://github.com/liferay/clay/commit/ec90630785725d043ca6fcca887ad970331859ff))
-   **@clayui/css:** customize Picker style in DatePicker ([26064de](https://github.com/liferay/clay/commit/26064debdd3b6cde034130f7cbf6ee360ce67c5e))
-   **@clayui/css:** Dropdown Menu adds dropdown-item-scroll styles ([08e3ab9](https://github.com/liferay/clay/commit/08e3ab9d276739a83d450a0cf0e04b86f32e3579))
-   **@clayui/css:** dropdown-menu-select inline-scroller should be taller ([320c166](https://github.com/liferay/clay/commit/320c166ff26de63b45f6dba09874a0b545d482ea))
-   **@clayui/css:** Mixins clay-dropdown-menu-variant adds dropdown-item-scroll ([f4ae8f1](https://github.com/liferay/clay/commit/f4ae8f12b13470d3d026a97de7467b705add2da4))
-   **@clayui/date-picker:** add Picker component to select year ([6c84e4a](https://github.com/liferay/clay/commit/6c84e4a16e1a3eab84ee54d0332606d571987678))

### Bug Fixes

-   **@clayui/autocomplete:** fix error keeping menu open after selecting option with `menuTrigger="focus"` ([5f305f7](https://github.com/liferay/clay/commit/5f305f7962677c5e0c2b1b7a366f507755fc9947))
-   **@clayui/autocomplete:** fixes error when losing reference to nodes at each rerender ([a28aa05](https://github.com/liferay/clay/commit/a28aa050ab3dbe8d337518361289f4a4fbc87cac))
-   **@clayui/autocomplete:** fixes error when not resetting visual focus when menu is closed by custom logic ([b45c87e](https://github.com/liferay/clay/commit/b45c87e15456639def329731a0fc0a038df87906))
-   **@clayui/multi-select:** fix error when changing active state from uncontrolled to controlled ([f6ef5be](https://github.com/liferay/clay/commit/f6ef5beff49f6e703c31694bca542f160be417af))
-   **@clayui/multi-select:** fix error when not invoking method of `onFocus` when defined ([934878a](https://github.com/liferay/clay/commit/934878ab4a1ee74735a4b06369e2581826acf9b2))

### Bug Fixes

-   **@clayui/core:** fix the order of importance for using the item id of a collection ([b40958e](https://github.com/liferay/clay/commit/b40958e87f2b9442c7caae87209837a3a0398592))

### Bug Fixes

-   **@clayui/autocomplete:** removes unnecessary use of the `dropdown-menu-indicator-start` CSS class ([ce09cd8](https://github.com/liferay/clay/commit/ce09cd814bf547e3437a45956f315a0588c52114))
-   **@clayui/core:** Add the missing id so that the screen reader makes a correct reading ([ff5df5c](https://github.com/liferay/clay/commit/ff5df5c29b6a37a19c1c6cb7537b6e9c81f28603))
-   **@clayui/core:** fix error when submitting the form ([75e07fe](https://github.com/liferay/clay/commit/75e07fef03a3695d14bef73cba84ff585193883e))
-   **@clayui/core:** fix typo ([665a5e3](https://github.com/liferay/clay/commit/665a5e3c6c6e7199fea8dcfaf7c3cdc5441bb915))
-   **@clayui/css:** Cadmin btn-sm icons should be 16px x 16px ([ca05132](https://github.com/liferay/clay/commit/ca05132d1b37e451c212906eee7a22428e6cfebd))
-   **@clayui/css:** Menubar removes negative margins in mobile and sync up Cadmin styles with Atlas ([a490fe6](https://github.com/liferay/clay/commit/a490fe661f572b4049273dd4251f98bb9fbf2904))
-   **@clayui/css:** Menubar update hover and active borders ([297a214](https://github.com/liferay/clay/commit/297a214a34f57ff558fea7c69b0b89ee058e8916))
-   **@clayui/css:** Mixins clay-css output truncated text override .c-prefers-expanded-text selectors ([8dfeafd](https://github.com/liferay/clay/commit/8dfeafddb3d726ee7cee722fa2893c844667d645))
-   **@clayui/css:** Mixins clay-link add more options to customize in show state ([2c83bfd](https://github.com/liferay/clay/commit/2c83bfd06d0e6af36ea518580fad099c1e8ee21e))
-   **@clayui/css:** Mixins text-truncate should use clay-css mixin to output .c-prefers-expanded-text selectors ([d0d7fdd](https://github.com/liferay/clay/commit/d0d7fdd5f01edd6f3740aad8ffc39e9280ddf811))
-   **@clayui/css:** More complex input-groups should accommodate inset focus styles ([3061ded](https://github.com/liferay/clay/commit/3061ded11e39ac15b8c75b7f514eb0c91f253b63))
-   **@clayui/css:** Pagination update hover and active borders ([abdce0e](https://github.com/liferay/clay/commit/abdce0e2fa2258d51327c0781c43ebbbd16eb9bc))
-   **@clayui/css:** Remove dependence on \_nav variables in \_icons.scss ([bf8cb83](https://github.com/liferay/clay/commit/bf8cb83ef81309478cc1776736bf8cd0cc6e8aa1))
-   **@clayui/css:** Transitions should work for .input-group-item.focus ([d3acc25](https://github.com/liferay/clay/commit/d3acc259c71b02b50a93a3d527ed3be4afb3902e))
-   **@clayui/multi-select:** explicitly add the `active` API in the component's typing ([e956828](https://github.com/liferay/clay/commit/e95682814d3ec7ab45e65e41bba291a2da023e74))
-   **@clayui/multi-select:** maintains backwards compatibility with the `menuRenderer` API but without the new features ([63ffb84](https://github.com/liferay/clay/commit/63ffb8449ec2c8e14d433be360bae8b29a6962e3))

### Features

-   **@clayui/css:** Adds global classes to configure accessibility ([232e15a](https://github.com/liferay/clay/commit/232e15ad8700d89ec9c004653a5a188bcbe25fa9))
-   **@clayui/css:** SVG Icon adds accessibility.svg ([f2e5ff5](https://github.com/liferay/clay/commit/f2e5ff506288f86e236274fb46dd6f65fb4a33da))
-   **@clayui/css:** SVG Icons adds stars.svg ([dafbfbd](https://github.com/liferay/clay/commit/dafbfbd0d8c5244cbcc7f6a844504128304c2db1))
-   **@clayui/multi-select:** adds the possibility to ignore the item's default behavior ([5412700](https://github.com/liferay/clay/commit/5412700e3118575588907ff551a27c594d9fe4d8))
-   **@clayui/multi-select:** deprecated the `liveRegion` and `hotkeysDescription` APIs to use the `messages` API ([2cf0766](https://github.com/liferay/clay/commit/2cf07669bc295918e4bacbbaaffc1c4996b67a65))

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:commerce

**Comment by eltonccdantas** [comment]
ci:test:commerce-functional

**Comment by john-co** [comment]
ci:test:clay

**Comment by matuzalemsteles** [comment]
@eltonccdantas it seems that the vast majority will really need to update the test paths, the implementation of MultiSelect and Autocomplete has different markups now compared to the previous version, so it can be breaking a lot of tests with this behavior.

I noticed the test case `LocalFile.BlogsSharing#CanShareWithUpdatePermissions` may need to be updated as well, I think the problem with the double click on the option may also be affecting the tests, I will focus on that now, I noticed another error that is related to this issue at Clay https://github.com/liferay/clay/issues/5580, as I already fixed this I'm going to do a patch release to add the update here as well.

Can you verify if these are really problems with updating the paths?

**Comment by eltonccdantas** [comment]
> @eltonccdantas it seems that the vast majority will really need to update the test paths, the implementation of MultiSelect and Autocomplete has different markups now compared to the previous version, so it can be breaking a lot of tests with this behavior.
> 
> I noticed the test case `LocalFile.BlogsSharing#CanShareWithUpdatePermissions` may need to be updated as well, I think the problem with the double click on the option may also be affecting the tests, I will focus on that now, I noticed another error that is related to this issue at Clay [liferay/clay#5580](https://github.com/liferay/clay/issues/5580), as I already fixed this I'm going to do a patch release to add the update here as well.
> 
> Can you verify if these are really problems with updating the paths?

Sure, I will work on the needed fixes concerning `BlogsSharing` as you suggested or any other component... I am also waiting on people from Commerce to see what's best for us, whether they're going to work on it or let us try to fix them.

**Comment by victoroscuro** [comment]
Hi @matuzalemsteles and @eltonccdantas, we've identified problems affecting a few Commerce functionalities (a couple would be blockers) @pietrobocale explained in a dedicated slack thread, please take a look. Should you need any help in reproducing them, please let us know.

**Comment by eltonccdantas** [comment]
Hey @matuzalemsteles, I saw that `LocalFile.BlogsSharing#CanShareWithUpdatePermissions` is failing due to the same issue as before, it needs to be clicked twice to enable the "Share" button.

https://github.com/liferay-peds/liferay-portal/assets/63858122/486add50-d110-4261-a314-23e47d2caaba

**Comment by eltonccdantas** [comment]
I worked on `DMSharing` tests and after fixing some stuff, they failed at the same point where the user has to click twice to make it work.

It's better I work on those fixes after this issue concerning clicking twice is solved, maybe some paths change again and I'll work twice on it... Feel free to reach me if you need any other thing for working on this pull request, I'll keep an eye on it 👁️, and as soon as you push the fix, I'll run the necessary suites and analyze the results. 👨🏻‍💻

**Comment by matuzalemsteles** [comment]
Thanks guys for investigating I'll take a look at these tests and try to reproduce locally to understand the issues. The double-click bug has already been fixed in Clay I'm going to send now send a commit that updates to the new version, so it's easier to see what these tests look like.

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:commerce

**Comment by victoroscuro** [comment]
Hey @matuzalemsteles @eltonccdantas some problems still persist. Please take a look at the slack thread. @pietrobocale

**Comment by eltonccdantas** [comment]
ci:test:commerce

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:commerce

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
Hey @eltonccdantas fixes some cases of commerce, one that was from Create Account and quick add to cart where the multi select was not showing the menu correctly. I couldn't reproduce the steps for the case involving Organization Management, could someone add the steps to get to this screen?

**Comment by pietrobocale** [comment]
Hey @matuzalemsteles and @eltonccdantas, I added a video on Slack that will help you to use the Organization Management

https://liferay.slack.com/archives/C01BZ7ZJ08M/p1687250356509839?thread_ts=1686849432.736419&cid=C01BZ7ZJ08M

**Comment by eltonccdantas** [comment]
> Hey @matuzalemsteles and @eltonccdantas, I added a video on Slack that will help you to use the Organization Management
> 
> https://liferay.slack.com/archives/C01BZ7ZJ08M/p1687250356509839?thread_ts=1686849432.736419&cid=C01BZ7ZJ08M

Thanks @pietrobocale

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:commerce

**Comment by eltonccdantas** [comment]
ci:test:commerce

**Comment by eltonccdantas** [comment]
ci:test:commerce

**Comment by john-co** [comment]
ci:test:commerce

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:relevant:norebase

**Comment by john-co** [comment]
ci:test:commerce:norebase

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:commerce

**Comment by eltonccdantas** [comment]
[Poshi Report](https://drive.google.com/file/d/1hyPrkZxdLTGed1zrisD9J4uAQ_6UMHMp/view?usp=sharing) for CanAssociateExistingAccountUsingWidget

**Comment by john-co** [comment]
ci:test:commerce

**Comment by john-co** [comment]
ci:test:clay

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:stop

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:commerce

**Comment by eltonccdantas** [comment]
ci:test:commerce-functional

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:commerce-functional

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
`ci:test:commerce` [Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1687484559103&testrayRunIdA=2358787188&testrayRunIdB=2358024886)

Discovered 1 test failure was related: [CommerceOrganizationManagementWidget#CanAssociateExistingAccountUsingWidget](https://testray.liferay.com/home/-/testray/case_results/2358788921) - I force pushed a test fix for it.

**Comment by john-co** [comment]
Waiting for `ci:test:relevant` results to populate in Testray. Will try and forward if I see there's no other significant related test failures.

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Ok to forward from QA perspective.

`:test:relevant` [Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2358649618&testrayRunIdA=2358868845&statusB=2)

**Comment by john-co** [comment]
ci:forward:force

**Comment by ethib137** [comment]
ci:forward:force

**Comment by eltonccdantas** [comment]
Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/136807

**Pull request closed without merging**
