### PR TITLE
LPS-198123 Return detailed message for exception.

### PR DESCRIPTION
**Pull request by SelenaAungst**
https://liferay.atlassian.net/browse/LPS-198123

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Hey @SelenaAungst thanks for working on this... I did some searching through the source code for `LanguageUtil` inside of `*Exception.java` classes...  it looks like the standard approach for this in Liferay is to create a new method `getLocalizedMessage` that will return the translated message. This should then be called wherever the translated message is needed.

You can see an example [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/info/info-api/src/main/java/com/liferay/info/exception/InfoFormFileUploadException.java#L31). 

Additionally, based on the location of the code, I think this will be owned by frontend-infra: https://docs.google.com/spreadsheets/d/1azJIucqKawYB7TMCnUIfmNac9iQEfkPDR5JKM6Nzia0/edit#gid=1959442404&range=E266 so the PR should be sent there.

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated :heavy_check_mark: 

Ok to forward from QA perspective. Pending dev approval.

**Comment by SelenaAungst** [comment]
Thank you @ethib137 and @john-co! I will make those changes and send a new PR to frontend-infra.

**Comment by SelenaAungst** [comment]
Based on review from the frontend-infra team here: https://github.com/liferay-frontend/liferay-portal/pull/3760#issuecomment-1770124906 this PR is OK to forward

**Comment by SelenaAungst** [comment]
ci:forward

**Comment by SelenaAungst** [comment]
Forwarded manually: https://github.com/brianchandotcom/liferay-portal/pull/142537

**Pull request closed without merging**
