### PR TITLE
LPS-190476 New type of Feature Flag: deprecation

### PR DESCRIPTION
**Pull request by thiago-buarqque**
This is just a conflict resolution caused by the changes introduced [here](https://github.com/liferay-peds/liferay-portal/commit/c060f408353c0ac02d5964e8d05aadaa4fca693c#diff-2d1ad7a01890ba33bbdde50fd944ef66d31e13b956f58040c05b3955221055bcR3) after my PR got in Brian's queue. Original PR is #216.

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:stop:relevant

**Comment by thiago-buarqque** [comment]
SF and CI fails are unrelated to my changes (for weeks now, see previous PR in the description). Forwarding it directly to Brian.

See https://github.com/brianchandotcom/liferay-portal/pull/140185

**Comment by eltonccdantas** [comment]
> SF and CI fails are unrelated to my changes (for weeks now, see previous PR in the description). Forwarding it directly to Brian.
> 
> See [brianchandotcom#140185](https://github.com/brianchandotcom/liferay-portal/pull/140185)

Just for documenting our clue the failures are unrelated to this pull request: [comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1693852357226&testrayRunIdA=2418030551&testrayRunIdB=2418438759)

**Pull request closed without merging**
