### PR TITLE
LPS-188971 remove tabindex attributes from ddm role group divs

### PR DESCRIPTION
**Pull request by pat270**
https://liferay.atlassian.net/browse/LPS-188971

I don't think this is PEDs related, but I'm not sure which team to send it to. 

@john-co That group shouldn’t be receiving focus via tab. I traced it down to a couple `tabindex` attributes that were added in https://liferay.atlassian.net/browse/LPS-151194 (https://github.com/liferay/liferay-portal/blame/8a8ccf6182cddaa04da6992d2426014dea057cfb/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/resources/META-INF/resources/FieldBase/ReactFieldBase.es.js#L254) and https://liferay.atlassian.net/browse/LPS-179541 (https://github.com/liferay/liferay-portal/blame/master/modules/apps/data-engine/data-engine-js-components-web/src/main/resources/META-INF/resources/js/core/components/Pages.es.js#L70). 

I removed those `tabindex` attributes. 

@georgel-pop-lr is there a specific accessibility reason those were added? My understanding is screen readers will announce the content inside `role="group"` without `tabindex`. I'm not sure why we are including it in page's the tab order.

### CODE REVIEW

**Comment by ethib137** [comment]
Also, it looks like the same PR that introduced that tabindex also added in role="group" for fieldsets. This isn't need since fieldsets implicitly have the group role. Probably shouldn't be changed in this PR though...

Also data engine is owned by the BPM team and based on their PR guidelines on confluence this should be sent to @liferay-forms

**Comment by georgel-pop-lr** [comment]
> role="group"

Hi,

Yes you are right, this should go to liferay-forms team.

Could you point out where did you see it? 

Regards.

**Comment by georgel-pop-lr** [comment]
> https://liferay.atlassian.net/browse/LPS-188971
> 
> I don't think this is PEDs related, but I'm not sure which team to send it to.
> 
> @john-co That group shouldn’t be receiving focus via tab. I traced it down to a couple `tabindex` attributes that were added in https://liferay.atlassian.net/browse/LPS-151194 (https://github.com/liferay/liferay-portal/blame/8a8ccf6182cddaa04da6992d2426014dea057cfb/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/resources/META-INF/resources/FieldBase/ReactFieldBase.es.js#L254) and https://liferay.atlassian.net/browse/LPS-179541 (https://github.com/liferay/liferay-portal/blame/master/modules/apps/data-engine/data-engine-js-components-web/src/main/resources/META-INF/resources/js/core/components/Pages.es.js#L70).
> 
> I removed those `tabindex` attributes.
> 
> @georgel-pop-lr is there a specific accessibility reason those were added? My understanding is screen readers will announce the content inside `role="group"` without `tabindex`. I'm not sure why we are including it in page's the tab order.

Hi,

This ReactFieldBase.es.js is the base of all the fields that a form can handle, so right now I don't remember all the cases, but for sure if you remove it from there it could create accessibility issues for some fields.

Regarding that I added tabindex to group as it wasn't accessibly by keyboard, if you think it is without it, then you could remove it.

Regards.

**Comment by pat270** [comment]
Forwarded to liferay-forms team, I'm going to close this.

**Comment by ethib137** [comment]
Hey @georgel-pop-lr this is where I saw that `role="group"` is added for fieldsets: https://github.com/brianchandotcom/liferay-portal/pull/132884/files#diff-e24cee579291babd4621a3cc2f45c41f3ac90a1a8ebdf8fd0d3267195717812aR256

**Pull request closed without merging**
