### PR TITLE
LPS-187583 Add Autom. Test FirstTimeSignInConfigUsesLocalStorageIfConfigNotChangedWhileSignedIn

### PR DESCRIPTION
**Pull request by eltonccdantas**
Ticket

Given new created user A
And new created user B
And guest user permissions
And default show underline is set to ON
// verify config is set to ON by default
When sign in as user A
And shows that guest preferences persist *** (added later)
And toggle show underline to OFF
And
sign out
And sign in as user B
And open accessibility menu 
Then show underline is set to ON

### CODE REVIEW

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by john-co** [comment]
Just started reviewing... :hourglass_flowing_sand:

**Review by john-co — APPROVED** [review]
Looks good to me! :sunglasses:

**Comment by john-co** [comment]
ci:test:accessibility-menu:nocompile

**Comment by john-co** [comment]
ci:forward

**Comment by eltonccdantas** [comment]
ci:forward:force

**Pull request closed without merging**
