### PR TITLE
LPS-196641 Create a FeatureFlagListener SPI

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-196641](https://issues.liferay.com/browse/LPS-196641).

Resent per [Brian's request](https://github.com/brianchandotcom/liferay-portal/pull/141570#issuecomment-1741592259).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:reevaluate:1277401_10212

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@eltonccdantas any concerns with this one?

**Comment by eltonccdantas** [comment]
> @eltonccdantas any concerns with this one?

Hey @drewbrokke , I had already left when you pinged me, sorry. I'll take a closer look at it now 🕵🏻

**Comment by eltonccdantas** [comment]
Hey @drewbrokke , The failures look unrelated, may we forward this one?

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1696505361904&testrayRunIdA=2435987911&testrayRunIdB=2436222675)

[testray-results.csv](https://github.com/liferay-peds/liferay-portal/files/12817816/testray-results.csv)

[VLookUp](https://docs.google.com/spreadsheets/d/11m6UAIv-y4PoPtHL1iQx9KPdtmhqw9G6/edit?usp=sharing&ouid=101533607319431228990&rtpof=true&sd=true)

**Comment by drewbrokke** [comment]
@eltonccdantas thanks for looking! Yes if this seems good to you, we can forward.

**Comment by drewbrokke** [comment]
@eltonccdantas any objections to forwarding this one?

**Comment by eltonccdantas** [comment]
ci:forward:force

**Comment by eltonccdantas** [comment]
> @eltonccdantas any objections to forwarding this one?

Nope.. I was in Q3 retro, didn't get the notification.

**Pull request closed without merging**
