### PR TITLE
LPS-188266 Update packages `@clayui/*` to v3.99.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**
### Bug Fixes

-   **@clayui/autocomplete:** fix bug not announcing available options when autocomplete is open ([1dc9581](https://github.com/liferay/clay/commit/1dc9581bd2e96b7cdf250bf02c4858c5df4eb833))
-   **@clayui/autocomplete:** fixes suppressing the `+` from the value when filtering the list ([1ba8356](https://github.com/liferay/clay/commit/1ba8356fce973dce24a63b5154e9ae9370c43562))
-   **@clayui/css:** Utilities forgot to add !important to some bg utils ([c164484](https://github.com/liferay/clay/commit/c164484abc0aeb4928c9f7b057f1d46ed42d8f95))
-   **@clayui/drop-down:** fixes error when restoring focus from DropDown ([5802f32](https://github.com/liferay/clay/commit/5802f32b885c0479e82c46ffcfdc99f0a5a0b461))
-   **@clayui/form:** adds the proper `role` to the switch component ([c3530c3](https://github.com/liferay/clay/commit/c3530c38f08b8679a4681f04da631259baef2654))
-   **@clayui/multi-select:** fixes error when not disabling the MultiSelect component ([51dafd3](https://github.com/liferay/clay/commit/51dafd3f729034f0cac40dce87315e8ad2ae413d))

### Features

-   **@clayui/core:** adds feature parity for `onItemMove` and `onItemHover` with drag and drop via keyboard ([dfa8e9e](https://github.com/liferay/clay/commit/dfa8e9ef86a43bb3f9a25aef7deb20abf215a783))
-   **@clayui/core:** allow returning false to cancel hover ([764210d](https://github.com/liferay/clay/commit/764210d3373495f0c3c8481ee25490250630c6a0))
-   **@clayui/core:** disable drop when not a valid target by `onItemHover` ([006eef6](https://github.com/liferay/clay/commit/006eef675d57ee8fb6daafb7321fb399872f8774))
-   **@clayui/css:** Utilities adds more text and bg color utilities ([5230949](https://github.com/liferay/clay/commit/5230949577407b21c96011eda3acfea4c2c3f1e7))

### CODE REVIEW

**Comment by eltonccdantas** [comment]
🕵🏻

**Comment by eltonccdantas** [comment]
Hey Matu, I've analyzed the failures, and according to this [comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2363564402&testrayRunIdA=2363437639&statusB=3) they seem to be unrelated to your pull request... 5 tests also [did not run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=6&testrayRunIdB=2363564402&testrayRunIdA=2363437639&statusB=3) but batch tests are not usually related to our changes, right?
image

**Comment by eltonccdantas** [comment]
ci:forward:force

**Comment by john-co** [comment]
ci:test:clay

**Comment by eltonccdantas** [comment]
Hey @john-co , should we run other test suites before?

**Comment by john-co** [comment]
ci:test:clay

**Comment by john-co** [comment]
Checkbox tests look unrelated. May want to double check the ClaySelect#MultipleCanBeConfigured test locally if the test fails again: https://testray.liferay.com/home/-/testray/case_results/2307091718

**Comment by eltonccdantas** [comment]
> Checkbox tests look unrelated. May want to double check the ClaySelect#MultipleCanBeConfigured test locally if the test fails again: https://testray.liferay.com/home/-/testray/case_results/2307091718

I was able to [reproduce it locally](https://gist.github.com/eltonccdantas/7a0716388e7c439f95c188097a79f21e) after downloading the bundle and etc.[ It works fine.](https://drive.google.com/file/d/1kVSiDcwJgd7uP7r5s0wFFWM6Dg-8wK3t/view?usp=sharing)

**Comment by eltonccdantas** [comment]
ci:forward:force

**Comment by eltonccdantas** [comment]
ci:forward:force

**Comment by eltonccdantas** [comment]
Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/137095

**Comment by john-co** [comment]
It didn't seem like js-unit test batch was included in `ci:test:relevant`...I asked if someone could double check the logic in [#qa-ci-infrastructure](https://liferay.slack.com/archives/CL3TWSMHQ/p1688145471371319?thread_ts=1686594558.718689&cid=CL3TWSMHQ)

**Comment by john-co** [comment]
ci:test:stable

**Comment by matuzalemsteles** [comment]
Thanks @john-co for checking.

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
Hey @matuzalemsteles, I see there are failures related to `semantic-versioning`:

[beanshell] 7 unique failures found.
[beanshell] functional-tomcat90-mysql57-jdk8/0/0(3)
[beanshell] 	LocalFile.ClayCheckbox#ParentMustBeCheckedIfAllChildrenAreChecked
[beanshell] 	LocalFile.ClayCheckbox#ParentMustBeIndeterminateIfSomeChildrenChecked
[beanshell] 	LocalFile.ClayCheckbox#ParentMustBeUncheckedIfNoChildrenChecked
[beanshell] modules-semantic-versioning-jdk8/0/4(0)
[beanshell] modules-semantic-versioning-jdk8/0/6(0)
[beanshell] semantic-versioning-jdk8/0/0(0)

Are these `semantic-versioning` test failures related to your changes?

Also, the `ClayCheckbox` tests are being fixed at another PR, am I right?

**Comment by matuzalemsteles** [comment]
@eltonccdantas 

> Are these semantic-versioning test failures related to your changes?

Yeah, not related to this PR.

> Also, the ClayCheckbox tests are being fixed at another PR, am I right?

Yeah, it will be fixed by PR #139

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
🕵🏻

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
In order to make sure the failures are unrelated, I decided to run `ci:test:relevant` again

**Comment by eltonccdantas** [comment]
ci:test:clay

**Comment by eltonccdantas** [comment]
After much investigation from @matuzalemsteles and me, we spotted a failure and he's already working on the fix, I'll continue the analysis as soon as I start working Tomorrow. 🕵🏻

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
Hey @matuzalemsteles, Failures on `js-unit-jdk8/0/0` might be related to your pull request

```
TestingLibraryElementError: Unable to find role="switch"
```

[analytics.analytics-settings-web.src.main.resources.META-INF.resources.js.components.people.__tests__.People renders component, clicks on "sync all" switch and check if contacts and accounts are all toggled](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/621425/testReport/junit/analytics.analytics-settings-web.src.main.resources.META-INF.resources.js.components.people/__tests__/People_renders_component__clicks_on__sync_all__switch_and_check_if_contacts_and_accounts_are_all_toggled/)

and 

[analytics.analytics-settings-web.src.main.resources.META-INF.resources.js.components.people.__tests__.People renders component, clicks on "Contacts" and "Accounts" switches and checks if "sync all" switch is toggled](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/621425/testReport/junit/analytics.analytics-settings-web.src.main.resources.META-INF.resources.js.components.people/__tests__/People_renders_component__clicks_on__Contacts__and__Accounts__switches_and_checks_if__sync_all__switch_is_toggled/)

**Comment by matuzalemsteles** [comment]
This is a bit strange actually the change was made to correct the change we made to the Toggle components having an ARIA attribute suitable for `switch` according to the result of this test it is still as a checkbox which makes me think that the CI does not it's including clay's update commit that makes this change I thought it was because the hash was the same as before it was reverted but it's not the same because i redid the commit to prevent that and also the test is passing locally.

I'm going to rebase with master and run the tests again.

**Comment by matuzalemsteles** [comment]
I redid the commits again, it seems that there was a problem with the commit to update the dependencies and the CI was not even running with that commit, so we were seeing it pass the tests.

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
I'll look at the results as soon as I get to the office Tomorrow morning.

**Comment by matuzalemsteles** [comment]
I made new changes to update the snapshot tests that were failing in the unit tests of the `dynamic-data-mapping-form-field-type` module, I also ran `gw packageRunTest` to run all the DXP unit tests and they passed, I'll run the relevant again.

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:stable

**Comment by eltonccdantas** [comment]
Hey @matuzalemsteles, after further investigation, the results from the last runs indicate that the failures are unrelated to your pull request.

[comparison run - a](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2373032563&testrayRunIdA=2372452216&statusB=3)

[comparison run - b](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2372293051&testrayRunIdA=2371302355&statusB=3)

[comparison of both runs](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2372293051&testrayRunIdA=2373032563&statusB=3)

**Comment by eltonccdantas** [comment]
ci:forward:force

**Pull request closed without merging**
