### PR TITLE
LPS-195764 Escape key

### PR DESCRIPTION
**Pull request by jonathanmccann**
https://liferay.atlassian.net/browse/LPS-195764

### CODE REVIEW

**Comment by eltonccdantas** [comment]
Hey @jonathanmccann, could you update the description to give us more context?

**Comment by ethib137** [comment]
ci:reevaluate:1397401_7490

**Review by ethib137 — APPROVED** [review]
Thanks @jonathanmccann , looks good to me as long as we get QA Approval.

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:stable

**Comment by eltonccdantas** [comment]
The failures are unrelated to your pull request.

[Comparison run ](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1695726457317&testrayRunIdA=2429962168&testrayRunIdB=2430573782)

**Comment by eltonccdantas** [comment]
ci:forward:force

**Pull request closed without merging**
