### PR TITLE
LPS-198287 Set overflow visible to avoid double scroll in a line

### PR DESCRIPTION
**Pull request by veroglez**
Hi guys!

In Echo team we have these two issues https://liferay.atlassian.net/browse/LPS-198287 and https://liferay.atlassian.net/browse/LPS-198284. These issues are related to the Code Mirror classes in cadmin. Could you review this change? 

Thanks in advance!

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by ethib137** [comment]
@pat270 can you review this?

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Review by pat270 — APPROVED** [review]

**Comment by pat270** [comment]
LGTM!

**Comment by pat270** [comment]
ci:forward

**Pull request closed without merging**
