### PR TITLE
LPS-178711 Update packages `@clayui/*` to v3.91.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**
### Bug Fixes

-   **@clayui/core:** Vertical Bar declare main mouse button as constant ([ccb1068](https://github.com/liferay/clay/commit/ccb1068c593032353754850a33b39734fb37b08b))
-   **@clayui/core:** Vertical Bar don't update panel if cursor is less or more than panel width ([781ffcc](https://github.com/liferay/clay/commit/781ffcc9d56c9bd223ca2050996f527179e71365))
-   **@clayui/core:** Vertical Bar stop updating panel after min/max width reached ([7541959](https://github.com/liferay/clay/commit/754195962f6ab24dda4e5f3f0f1da93bdcee48af))
-   **@clayui/css:** Navigation Bar focus outline should be rounded ([a9dfdc0](https://github.com/liferay/clay/commit/a9dfdc037fa832ffd84839bdb4dd4d7f4c640282))
-   **@clayui/css:** Removes nav-underline from Clay and Cadmin ([642c479](https://github.com/liferay/clay/commit/642c47964a48a1337220fd011ebcf4c5246455e0))
-   **@clayui/css:** Resizer shouldn't select text when dragging ([e2842c0](https://github.com/liferay/clay/commit/e2842c0cb455804de3a97d093c5a90df72f2c49f))
-   **@clayui/css:** Treeview btn should inherit component's color ([4e733f9](https://github.com/liferay/clay/commit/4e733f9fcb6b8f853f2150ba2bb2cce10f6e5c42))
-   **@clayui/pagination-bar:** fix bug in documentation example ([8924412](https://github.com/liferay/clay/commit/8924412729baa8a35f4e3729a632d5399fcab93f))
-   **@clayui/tabs:** Tabs deprecate `displayType` and `modern` attributes ([196abec](https://github.com/liferay/clay/commit/196abec5383d05f9af15af6893e9062fc32ba1c9))

### Features

-   **@clayui/core:** adds `panelWidth` controlled implementation ([96b6373](https://github.com/liferay/clay/commit/96b63738e4f32138c4222e4941cd98298179b5b8))
-   **@clayui/core:** Vertical Bar adds resizing to VerticalBar.Panel ([82fe064](https://github.com/liferay/clay/commit/82fe064122c9cd7caae8efa21bf700e874fe64a8))
-   **@clayui/css:** Atlas and Cadmin update nav-tabs styles ([2e7aae2](https://github.com/liferay/clay/commit/2e7aae2665b467d28f79c79a01060c0aca4edb00))
-   **@clayui/css:** Cadmin and Clay adds c-horizontal-resizer component ([9dec76c](https://github.com/liferay/clay/commit/9dec76c72f3e0e71ddc0ae59f310ab404bee697b))
-   **@clayui/tabs:** force style for tabs ([859ef65](https://github.com/liferay/clay/commit/859ef65a552c2b8ad04c04fec1ad505c53c6dd40))

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
cc @mateusralv

**Comment by mateusralv** [comment]
Hi @matuzalemsteles I found this failure and I don't think it is related to your PR but to certificates. I will run ci:test:relevant again because I think the CI team already solved it.
 
```
[parallel] Build "modules-integration-mysql57-jdk8/3/18" completed at https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/440163/. UNSTABLE
 [parallel] timestamp-check-failed failure detected at https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/180202/. This build will be reinvoked.
 [parallel] 
 [parallel] axisVariable=.*
 [parallel] console=javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: timestamp check failed
 [parallel] jobVariant=.*
 [parallel] name=timestamp-check-failed
 [parallel] notificationRecipients=qa-slave-verify-fail@liferay.com
 [parallel] topLevelJobName=.*(acceptance|portal-release|testsuite).*
 [parallel] Build "modules-integration-mysql57-jdk8/0/3" started at https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/26429/.
 [parallel] Build "modules-integration-mysql57-jdk8/2/8" completed at https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/309396/. UNSTABLE
 [parallel] Email sent to: qa-slave-verify-fail@liferay.com
 [parallel] Reinvoked: https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/180202/
 [parallel] Build "modules-compile-jdk8/0/1" invoked at https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master).
[beanshell] Downstream builds have been running for 3 minutes
[beanshell] 1 Starting  / 0 Missing  / 0 Queued  / 35 Running  / 166 Completed  / 202 Total 
     [echo] Generating Jenkins report.
```

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1679925485374&testrayRunIdA=2244646546&testrayRunIdB=2245248488)

**Comment by mateusralv** [comment]
I'm take a look 🕵🏽

**Comment by mateusralv** [comment]
Hi @matuzalemsteles The failures are not related! I'll forward manually 🚀 

[Testray comparison ](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1679939437331&testrayRunIdA=2246903191&testrayRunIdB=2247063963)

**Comment by mateusralv** [comment]
Forwarded manually to brianchandotcom: https://github.com/brianchandotcom/liferay-portal/pull/132419

**Comment by mateusralv** [comment]
ci:close

**Pull request closed without merging**
