### PR TITLE
LPS-191968 Add a featureFlagKey attribute to Meta.OCD and Meta.AD

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-191968](https://issues.liferay.com/browse/LPS-191968).

@ethib137 this takes a different approach by adding a dedicated attribute to the extended object/attribute definition annotations.

The dev can add this to the config interface class to control the entire configuration UI visibility with a feature flag:
```
@ExtendedObjectClassDefinition(featureFlagKey = "LPS-179483")
```

The dev can add this to an individual method on the config interface to control visibility on just that field in the UI:
```
@ExtendedAttributeDefinition(featureFlagKey = "LPS-179483")
```

This approach also avoids registering any new services, which was the problem with the visibility controller approach I took earlier.

Please let me know if you have any questions or concerns.

/cc @thiago-buarqque

### CODE REVIEW

**Comment by eltonccdantas** [comment]
🕵🏻

**Comment by eltonccdantas** [comment]
Hey @drewbrokke, I've analyzed your pull request and found the following:

[**com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormConverterTest > testGetWithSelectField**](https://testray.liferay.com/reports/production/logs/2023-07/test-1-32/test-portal-acceptance-pullrequest(master)/1093/modules-unit-jdk8/0/0/com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormConverterTest.txt.gz?authuser=0)

```

 java.lang.NullPointerException
		at com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormConverter._setDDMFormFieldVisibilityExpression(ConfigurationModelToDDMFormConverter.java:564)
		at com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormConverter._getDDMFormField(ConfigurationModelToDDMFormConverter.java:311)
		at com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormConverter._addDDMFormFields(ConfigurationModelToDDMFormConverter.java:229)
		at com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormConverter._addRequiredDDMFormFields(ConfigurationModelToDDMFormConverter.java:252)
		at com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormConverter.getDDMForm(ConfigurationModelToDDMFormConverter.java:80)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormConverter.getDDMForm(ConfigurationModelToDDMFormConverter.java:71)
		at com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormConverterTest.testGetWithSelectField(ConfigurationModelToDDMFormConverterTest.java:443) 
... 

```
**and**

[**com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormValuesConverterTest > testGetValuesByConfigurationAndNegativeCardinalityWithTextField**](https://testray.liferay.com/reports/production/logs/2023-07/test-1-32/test-portal-acceptance-pullrequest(master)/1093/modules-unit-jdk8/0/0/com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormValuesConverterTest.txt.gz?authuser=0)

```
java.lang.NullPointerException
		at com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormConverter._setDDMFormFieldVisibilityExpression(ConfigurationModelToDDMFormConverter.java:564)
		at com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormConverter._getDDMFormField(ConfigurationModelToDDMFormConverter.java:311)
		at com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormConverter._addDDMFormFields(ConfigurationModelToDDMFormConverter.java:229)
		at com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormConverter._addRequiredDDMFormFields(ConfigurationModelToDDMFormConverter.java:252)
		at com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormConverter.getDDMForm(ConfigurationModelToDDMFormConverter.java:80)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormConverter.getDDMForm(ConfigurationModelToDDMFormConverter.java:71)
		at com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormValuesConverterTest.getDDMForm(ConfigurationModelToDDMFormValuesConverterTest.java:402)
		at com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormValuesConverterTest.testGetValuesByConfigurationAndNegativeCardinalityWithTextField(ConfigurationModelToDDMFormValuesConverterTest.java:110)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
...
```

There is also an issue related to `semantic-versioning`... Would you be able to work on those fixes? Thanks!

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2396217516&testrayRunIdA=2395783501&statusB=3)

[testray-results.csv](https://github.com/liferay-peds/liferay-portal/files/12194287/testray-results.4.csv)

**Comment by eltonccdantas** [comment]
Meanwhile, I'll trigger another `ci:testrelevant` to double-check.

**Comment by eltonccdantas** [comment]
Yeah, the second run confirmed those two tests are being affected by the changes in your pull request...

[comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2396458222&testrayRunIdA=2395783501&statusB=3)

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:help

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
I'm in doubt about [LocalFile.Publications#CanReviewChangesWithManyDocuments](https://testray.liferay.com/home/-/testray/case_results/2396722846), so I triggered another run... Otherwise, it looks safe. Thank you for working on a fix for previous failures @drewbrokke!

**Comment by eltonccdantas** [comment]
BTW, could you add me as a collaborator to your repository in case there is any test fix to be done?

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
Hey @drewbrokke, some conflicts are impeding `ci:test:relevant` to run, would you be able to resolve them?

**Comment by drewbrokke** [comment]
@eltonccdantas yup, on it. Thanks!

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:tes:sf

**Comment by eltonccdantas** [comment]
ci:tes:sf

**Comment by eltonccdantas** [comment]
ci:test:stable

**Comment by eltonccdantas** [comment]
Failures seem to be unrelated to it.. if `ci:test:stable` does not pass, I'll manually forward it, right?

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1690819229952&testrayRunIdA=2397142169&testrayRunIdB=2397347592)

**Comment by eltonccdantas** [comment]
ci:forward:force

**Comment by eltonccdantas** [comment]
ci:forward:force

**Comment by eltonccdantas** [comment]
Feel free to forward it after the necessary dev review.

**Comment by drewbrokke** [comment]
@ethib137 I'll remove it

**Comment by drewbrokke** [comment]
ci:forward:force

**Comment by drewbrokke** [comment]
Thanks for the review @ethib137!

**Comment by eltonccdantas** [comment]
ci:forward:force

**Pull request closed without merging**
