### PR TITLE
LPS-195972 Fluid layout should apply to Applications Menu

### PR DESCRIPTION
**Pull request by pat270**
https://liferay.atlassian.net/browse/LPS-195972

applications-menu-full

### CODE REVIEW

**Comment by ethib137** [comment]
Hey @pat270 , the designs indicate that in addition to moving to full width there are some other changes needed. There should also be an update to the grid at different breakpoints and the tab for sites has slightly different styling. Can you update this PR accordingly. If you see any reasons why we shouldn't update to match this design, let me know and we can discuss changes with design/product. Thanks.

**Comment by pat270** [comment]
@ethib137 I think we need to have a discussion on xs view 575px and below. In the Figma file, `nav-tabs` gets converted to an accordion. We need to write a special component to achieve that. The way tabs are marked up doesn't convert well to accordion/panel style only via CSS.

I made the column changes, this is what it looks like:
1024px lg
1024-lg

768 md
768-md

**Comment by john-co** [comment]
Hi @pat270 @ethib137 while discussion is pending, can we close this PR so it doesn't create noise in the PR queue? We can reopen this when ready to for CI/PR review.

**Comment by ethib137** [comment]
Resent here: https://github.com/liferay-peds/liferay-portal/pull/275

**Pull request closed without merging**
