### PR TITLE
LPS-193450 Refactor `openAccessibilityMenu` Macro

### PR DESCRIPTION
**Pull request by eltonccdantas**
This PR aims at fixing the tests from `AccessibilityMenu.testcase` by refactoring the `openAccessibilityMenu` macro.

[Ticket](https://liferay.atlassian.net/browse/LPS-193450)

### CODE REVIEW

**Comment by eltonccdantas** [comment]
ci:test:accessibility-menu:nocompile

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Looks good to me! :sunglasses:

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
