### PR TITLE
LPS-187952 Add the `accessibility-menu-web` module to release build

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Just releasing the Accessibility Menu module for release build and also to run on the usual ant all build.

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:reevaluate:1307401_7017

**Comment by john-co** [comment]
**Related:**
[modules-integration-mysql57-jdk8_stable/0/2](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/611657/)

stacktrace
```
java.lang.AssertionError: Please update the Language.properties files for the following portlets: [com_liferay_accessibility_menu_web_portlet_AccessibilityMenuPortlet]
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.liferay.portlet.title.localization.test.PortletTitleTest.testPortletTitles(PortletTitleTest.java:74)
```

**Unrelated:**
[portal-license-smoke-mysql57-jdk8/0/0](https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/205713/)
known issue: https://liferay.atlassian.net/browse/COMMERCE-11878

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:stop

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Ok to forward from QA perspective. Pending dev approval.

**Comment by matuzalemsteles** [comment]
@john-co we can forward this manually.

**Comment by john-co** [comment]
ci:forward:force

**Pull request closed without merging**
