### PR TITLE
LPS-187799 & LPS-187798 - Add additional settings to the accessibility menu.

### PR DESCRIPTION
**Pull request by ethib137**
https://issues.liferay.com/browse/LPS-187799
https://issues.liferay.com/browse/LPS-187798

This PR adds two additional settings:
- "Expanded Text"
- "Increased Text Spacing"

Both of these settings will default to false.

Screenshot 2023-06-16 at 5 00 18 PM

### CODE REVIEW

**Comment by pat270** [comment]
@ethib137 working pretty good to me. Do you think move and permission should be underlined? Technically they're not a hyperlink, they open modals. Similarly, should dropdown menu toggles be underlined? I think we eventually need to discuss what constitutes a link that should be underlined.

btn-no-underline

**Comment by john-co** [comment]
Light preliminary manual testing from QA perspective did not discover any issues or regressions. Testing was scoped to "expanded text" and "increased text spacing" configurations applying their respective body class. Also light accessibility exploratory testing found no new issues. Test scenarios are pending review in https://liferay.atlassian.net/browse/LPS-188104.

**Review by matuzalemsteles — APPROVED** [review]
Looks good to me! I think the discussion of what an underline can be I think will always be only for cases that use anchors, in this example of the image I think it would not make sense to add an underline to action buttons that do not involve navigation except cases where the button handles a navigation to another page but nowadays this is not recommended it should always be a hyperlink for accessibility reasons.

**Comment by ethib137** [comment]
> @ethib137 working pretty good to me. Do you think move and permission should be underlined? Technically they're not a hyperlink, they open modals. Similarly, should dropdown menu toggles be underlined? I think we eventually need to discuss what constitutes a link that should be underlined.

Yep I agree with @matuzalemsteles . I think this is a perfect example of this setting doing what it should. It is now visually apparent what is a hyperlink and what is not. Thanks!

**Comment by ethib137** [comment]
ci:forward

**Pull request closed without merging**
