### PR TITLE
LPS-189279 fixes error of the TreeView example without the checkbox with indeterminate state

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Ticket: https://liferay.atlassian.net/browse/LPS-189279

The problem is that we made an internal change to use the value typed in the `key` property to have greater order of importance than the `id` key in the `items` data. This was breaking this example, so I just changed it. We don't consider this a regression because the behavior before was a bug.

### CODE REVIEW

**Comment by eltonccdantas** [comment]
ci:reevaluate:1337401_3976

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:clay

**Comment by eltonccdantas** [comment]
ci:reevaluate:1257401_1725

**Comment by eltonccdantas** [comment]
Hey @matuzalemsteles, I see many pull requests now sharing failures concerning `semantic-versioning`, are they related to your changes?

`[exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal...`

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:clay

**Comment by eltonccdantas** [comment]
Hey @matuzalemsteles, what do you think this failure message on [modules-integration-mysql57-jdk8_stable/0/2](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/189942/)?

` Portal log assert failure, see above log for more information:  HHH000315: Exception executing batch [java.sql.BatchUpdateException: Duplicate entry '20096-com.liferay.commerce.product-4-com.liferay.commerce.produc' for key 'IX_A9FF4B2C'], SQL: insert into ResourcePermission (mvccVersion, ctCollectionId, companyId, name, scope, primKey, primKeyId, roleId, ownerId, actionIds, viewActionId, resourcePermissionId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

`junit.framework.AssertionFailedError: 
HHH000315: Exception executing batch [java.sql.BatchUpdateException: Duplicate entry '20096-com.liferay.commerce.product-4-com.liferay.commerce.produc' for key 'IX_A9FF4B2C'], SQL: insert into ResourcePermission (mvccVersion, ctCollectionId, companyId, name, scope, primKey, primKeyId, roleId, ownerId, actionIds, viewActionId, resourcePermissionId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:171)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:98)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:88)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:86)`


This is the only thing I would worry about, the other failures seem to be unrelated to your pull request.

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:clay

**Comment by matuzalemsteles** [comment]
Hey @eltonccdantas these tests are unrelated i would say the only tests we should be concerned about would be the ones in the clay suite because this change is only in a sample test module.

**Comment by eltonccdantas** [comment]
> Hey @eltonccdantas these tests are unrelated i would say the only tests we should be concerned about would be the ones in the clay suite because this change is only in a sample test module.




Alright @matuzalemsteles, I've analyzed the failures and they look unrelated to your pull request

[comparison run - clay](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1688579593432&testrayRunIdA=2371302355&testrayRunIdB=2371775259)

**Comment by eltonccdantas** [comment]
ci:forward:force

**Pull request closed without merging**
