### PR TITLE
LPS-198335 - Remove unneeded h4

### PR DESCRIPTION
**Pull request by marcoscv-work**
After PR headers hierarchy is not broken:

image

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
SF no related to mi PR

**Comment by eltonccdantas** [comment]
The failures are unrelated. It seems safe to forward from a QA perspective.

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1696620733666&testrayRunIdA=2437403411&testrayRunIdB=2437614607)

**Comment by ethib137** [comment]
@pat270 can you review this and forward it if you don't see any issues?

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
Hey @marcoscv-work, do you have any guesses on what's causing that SF failure?

**Comment by marcoscv-work** [comment]
My [only one commit](https://github.com/liferay-peds/liferay-portal/pull/315/commits/d58d702f1aed93d1717d4e29266ff0db8a4e3db6) is not modifying `generate_webdav_password .jsp` so I'm rebasing and testing again.

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
Let me check it🕵🏻

**Comment by eltonccdantas** [comment]
The failures seem to be unrelated. 🎉 
[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1697025964314&testrayRunIdA=2438944747&testrayRunIdB=2439072098)

**Comment by eltonccdantas** [comment]
Waiting on @pat270 to review before forwarding it.

**Comment by eltonccdantas** [comment]
ci:test:stable

**Comment by pat270** [comment]
LGTM!

**Comment by pat270** [comment]
ci:forward

**Comment by pat270** [comment]
@eltonccdantas can we manually forward this?

**Comment by john-co** [comment]
ci:forward:force

looks unrelated

**Pull request closed without merging**
