### PR TITLE
LPS-195844

### PR DESCRIPTION
**Pull request by mbowerman**
Re-sending from https://github.com/brianchandotcom/liferay-portal/pull/140803, which was rejected by Brian Chan because he wanted the generic upgrade process moved out of portal-kernel. Originally I was just going to move it into portal-impl like he wanted, but this led to other problems such as now I can't use the `CompanyLocalServiceUtil` class anymore due to our SF requirements there (which I need to do to handle DB partitioning cases safely). When I discussed with BChan in person it seemed like he was OK with keeping it in `portal-kernel` if I included multiple usages of it in the PR.

Therefore, I'm resending this with an extra usage of the new Upgrade. This was achieved by refactoring an existing upgrade which did the same thing (also, I'm pretty sure that my upgrade is more performant, since the old version of the upgrade fetched a bunch of ResourcePermissions unnecessarily and then manually filtered out all the ones that didn't have the Guest roleId). I tested it by starting on 7.0 (before [LPS-76419](https://liferay.atlassian.net/browse/LPS-76419) was merged), then setting a bunch of now-unsupported ResourcePermissions for the Guest role and the Power User role, upgraded to master with my fix deployed, and I verified that the specific guest-unsupported ResourcePermissions became unset for the Guest ResourcePermissions but not for the Power User ResourcePermissions.

There's a third use case coming for this upgrade (see Slack discussion thread [here](https://liferay.slack.com/archives/C0A1Z5FJL/p1695326055106799)), and I was originally going to include it in this pull, but it sounds like it may take them a while to hash out which specific actions should be set as guest-unsupported, so I just decided to go ahead and submit this as-is for now.

Original comment:
> # Motivation
> It is possible to set the Site Settings > Site: View Site and Asset Library Administration Menu permission for the Guest role. If you do so, then Liferay will run the logic to try to render the Control Menu for the Guest user, because it detects that the Site Administration Menu should be visible to them.
> 
> This results in a NullPointerException being thrown any time the Guest user does anything on the Site. This issue started occurring after [LPS-172659](https://liferay.atlassian.net/browse/LPS-172659), because [LPS-172659](https://liferay.atlassian.net/browse/LPS-172659) changed the logic of how we decide to render the Product Navigation Menu vs rendering the Pages Tree in the Control Menu. Prior to [LPS-172659](https://liferay.atlassian.net/browse/LPS-172659), we would decide to render neither the Product Navigation Menu nor the Pages Tree for the Guest user in this scenario. After [LPS-172659](https://liferay.atlassian.net/browse/LPS-172659), we now render the Product Navigation Menu for the Guest user in this scenario. This results in a NullPointerException being thrown, since we rightly don’t anticipate the possibility of attempting to render the Product Navigation Menu for the Guest user.
> 
> See ticket here: [LPS-195844](https://liferay.atlassian.net/browse/LPS-195844)
> 
> # Proposed Solution
> First, I added logic to always refuse to show the Product Navigation Menu if the user is the Guest user. This ensures that if we ever accidentally expose a Control Panel Key's View permission to the Guest user, we still do not render the Product Navigation Menu for them.
> 
> Second, I moved the "View Site and Asset Library Administration" permission, along with the "Configure Portlets" permission, to guest-unsupported, to ensure that the Guest cannot be allowed to have these permissions. I also added the upgrade process to remove these permissions from the Guest role in case if the Guest role was already granted them.
> 
> # Steps to Verify
> 1. Start up Liferay and log in as the admin user.
> 2. Add the Site Settings > Site: View Site and Asset Library Administration Menu permission to the Guest role.
> 3. Log out and visit the portal as a Guest user.
> 
> **Expected Result:** There would be no errors in the logs.
> **Actual Result:** The following error occurs in the logs: https://gist.github.com/mbowerman/b2db1ec2e593d732d9319e082160f0c6

### CODE REVIEW

**Comment by ethib137** [comment]
ci:reevaluate:1357401_4610

**Comment by eltonccdantas** [comment]
🕵🏻

**Comment by eltonccdantas** [comment]
The failures are unrelated to your changes.

[comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2429849045&testrayRunIdA=2428672771&statusB=3)

`com.liferay.data.engine.rest.resource.v2_0.test.DataDefinitionResourceTest` seems to be unique, but I downloaded the bundle [ran the test locally and it passed](https://gist.github.com/eltonccdantas/826f4e4d8d7e02d9d4c901c955c36c07). Therefore, it looks safe to forward from a QA perspective.

**Comment by eltonccdantas** [comment]
Hey @ethib137 and @mbowerman, may we forward this one or you're still going to modify it?

**Review by ethib137 — APPROVED** [review]
Thanks @mbowerman ... Looks good to me. 

@eltonccdantas feel free to forward.

**Comment by eltonccdantas** [comment]
Hey, having a second look... should we worry about that semantic versioning error?

image

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Still looks good from my side. Once we can get QA approval, feel free to forward.

**Comment by eltonccdantas** [comment]
🕵🏻

**Comment by eltonccdantas** [comment]
The failures are unrelated. 🎉 

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1695725126737&testrayRunIdA=2429962168&testrayRunIdB=2430562679)

**Comment by eltonccdantas** [comment]
ci:forward:force

**Comment by eltonccdantas** [comment]
ci:test:stable

**Comment by eltonccdantas** [comment]
Hey @mbowerman, it seems there's a conflict ongoing, would you be able to fix that?

**Comment by eltonccdantas** [comment]
No problem, I fetched the PR and pushed the update.

**Comment by eltonccdantas** [comment]
ci:test:stable

**Comment by eltonccdantas** [comment]
ci:forward:force

**Pull request closed without merging**
