### PR TITLE
LPS-193580 Remove fixed height on sign in modal

### PR DESCRIPTION
**Pull request by pat270**
https://liferay.atlassian.net/browse/LPS-193580

This allows the sign in modal to grow without overflow if the content is short enough to fit in the window. With the fixed height, even a small change like font-size: 16px, it will show a scrollbar.

signinmodal

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:stop

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:reevaluate:1327401_1512

**Comment by eltonccdantas** [comment]
Hey @pat270, Although there's a failure on this [comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1692361658223&testrayRunIdA=2407585495&testrayRunIdB=2407449656), I downloaded the bundle, ran the test locally and it passed... Is any other dev review needed?

**Review by ethib137 — APPROVED** [review]
LGTM. Thanks @pat270

**Comment by ethib137** [comment]
ci:forward:force

**Pull request closed without merging**
