### PR TITLE
LPS-188470 Fix feature flag tests

### PR DESCRIPTION
**Pull request by john-co**
**Description**
Fix feature flag tests

**Test Plan**
- [x] FeatureFlag.testcase passes

**JIRA TICKET**
https://issues.liferay.com/browse/LPS-188470

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:peds-sm:nocompile

**Comment by john-co** [comment]
ci:test:peds-sm

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:stop

**Comment by john-co** [comment]
ci:test:peds-sm

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:peds-sm:nocompile

**Comment by eltonccdantas** [comment]
ci:test:peds-sm

**Comment by eltonccdantas** [comment]
ci:reevaluate:1397401_5783

**Comment by eltonccdantas** [comment]
ci:test:peds-sm

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:peds-sm

**Comment by eltonccdantas** [comment]
ci:forward

**Comment by eltonccdantas** [comment]
ci:forward

**Comment by john-co** [comment]
Hi @eltonccdantas , where did you see the functional tests for feature flags pass on CI?

**Comment by eltonccdantas** [comment]
> Hi @eltonccdantas , where did you see the functional tests for feature flags pass on CI?

Hey @john-co, I looked for failures actually and since they were not found in the comparison, I decided to forward...  I just checked them on the [acceptance layer](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=2377322480&testrayComponentId=2125949714) now and they are all green.

image

**Pull request closed without merging**
