### PR TITLE
LPS-186425 - Test Fix for LanguageOverrideExportImport#CanViewFileUploadFieldIsRequired

### PR DESCRIPTION
**Pull request by eltonccdantas**
This PR aims to fix **LanguageOverrideExportImport#CanViewFileUploadFieldIsRequired** test by simply updating the text attributed to the variable.

[Poshi  Report](https://drive.google.com/file/d/1btpL4KclkL30i29wjh2m_j3Vf2wizUzj/view?usp=sharing)

[Jira Ticket](https://issues.liferay.com/browse/LPS-186425)

### CODE REVIEW

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:peds-sm

**Comment by john-co** [comment]
Looks good to me! :sunglasses:

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
ci:test:peds-sm

**Pull request closed without merging**
