### PR TITLE
LPS-192353

### PR DESCRIPTION
**Pull request by SelenaAungst**
https://liferay.atlassian.net/browse/LPS-192353

The ARC toolkit extension found the following error for the paragraph ddm form field type:
WCAG 2.1: 4.1.2 Name, Role, Value - The element has been placed in the Tab order using tabIndex="0", but it lacks a specific role="..." attribute.

I saw a solution to a similar issue where role: none was added. I tested this and it did make the error go away in the ARC test, but I am not sure if this is the best solution. Please let me know if something needs to be changed for this!

### CODE REVIEW

**Comment by ethib137** [comment]
Hey @SelenaAungst, a paragraph shouldn't be focusable since it's not an interactive element. My first thought is that we should find a way to make sure that tabindex="0" is not added to the paragraph rather than adding an additional role. This looks like a rather complicated bit of code, so you'll want to spend some time going through the git blame to see why this was added to begin with and make sure you're not causing any regressions in the process. Let me know if you run into any issues.

**Comment by SelenaAungst** [comment]
Thanks for looking into this @ethib137!
It looks like this tabindex was added here https://github.com/brianchandotcom/liferay-portal/commit/19e9e979653c367ca8a9bb373af10b0b84eb4651 for https://liferay.atlassian.net/browse/LPS-176140 to allow elements to be focused during validation, for example if something within the paragraph is invalid or the field is required. Should this tabindex still not apply to the paragraph field?

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
I'll take a look at it as soon as I start work tomorrow morning 🕵🏻

**Comment by ethib137** [comment]
@eltonccdantas you can hold off on testing this since I think we will be making additional changes to this PR.

**Comment by ethib137** [comment]
> It looks like this tabindex was added here https://github.com/brianchandotcom/liferay-portal/commit/19e9e979653c367ca8a9bb373af10b0b84eb4651 for https://liferay.atlassian.net/browse/LPS-176140 to allow elements to be focused during validation, for example if something within the paragraph is invalid or the field is required. Should this tabindex still not apply to the paragraph field?

Hey @SelenaAungst , the paragraph shouldn't need to be focusable in this case, because the paragraph cannot have an error or be required. It's not an input it's just plain text used to add an intro or extra information to a form. The [ticket](https://liferay.atlassian.net/browse/LPS-176140) that added this indicates that it was trying to make text and numeric inputs focusable. It seems like making the paragraph focusable was likely an unintended side affect. 

So, we should be looking for a fix that removes tabindex from paragraphs while preserving the previous fix for text and numeric inputs.

**Comment by eltonccdantas** [comment]
> @eltonccdantas you can hold off on testing this since I think we will be making additional changes to this PR.

Thanks @ethib137!

**Comment by SelenaAungst** [comment]
Thank you for explaining @ethib137! I will look into how this can be removed for just parargraphs.

**Comment by eltonccdantas** [comment]
Hey @SelenaAungst, is there anything I can do from a QA perspective for helping you to work on this PR?

**Comment by SelenaAungst** [comment]
Hi @eltonccdantas, 
Thanks for checking up on this one! I think I can close it for now, I ended up finding a different ticket that caused this issue and opening a PTR, so I am going that route for the solution.

**Pull request closed without merging**
