### PR TITLE
LPS-196641 Create a FeatureFlagListener SPI

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-196641](https://issues.liferay.com/browse/LPS-196641).<br/><br/>/cc @shuyangzhou

### CODE REVIEW

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Closing to update according to Shuyang's feedback.

**Comment by drewbrokke** [comment]
ci:close

**Pull request closed without merging**
