### PR TITLE
LPS-179992 - Rename dropdown for Filter and Order in Feature Flags

### PR DESCRIPTION
**Pull request by ethib137**
https://issues.liferay.com/browse/LPS-179992

Rename dropdown to use standard label for filter: "Filter by Status".

Remove filter-by-x language key, since x will be a single-word-translation key that provides no context for how to translate it. single-word-translation keys should be avoided whenever possible.

Added a new property `label` to the internal Filter Class so that a full label can be set for each filter.

@drewbrokke could you let me know if my changes look okay to you?

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
@drewbrokke were you able to test the Evan change?
If it is ok we can go ahead with it.

**Comment by marcoscv-work** [comment]
> Hey @marcoscv-work this seems fine to me, though I did have a conversation with Evan about a deeper rename of the code itself.
> 
> This is necessary because the current meaning of `status` in the case of feature flags has to do with whether it is dev, beta, or release. In reality Evan and I agree that this should be called "type" and we have agreement from product about it too.
> 
> However, it poses a problem with this pull because Brian will probably have an issue with the collision/inconsistency (`status` here means enabled/disabled, everywhere else it means the above types). I am ok forwarding this but we should make sure that the next task is set and is not forgotten.
> 
> Thoughts?

Sounds good to me, we could create a new task for this in order not to forget it

**Review by drewbrokke — APPROVED** [review]

**Comment by marcoscv-work** [comment]
ci:forward

**Comment by drewbrokke** [comment]
See https://issues.liferay.com/browse/LPS-182764

**Pull request closed without merging**
