### PR TITLE
LPS-192061 Refactor AccessibilityMenu.testcase and .macro

### PR DESCRIPTION
**Pull request by eltonccdantas**
Refactor the tests into this file for optimizing code quality.

### CODE REVIEW

**Comment by eltonccdantas** [comment]
ci:help

**Comment by eltonccdantas** [comment]
ci:test:accessibility-menu

**Comment by john-co** [comment]
Just started reviewing... :hourglass_flowing_sand:

**Review by john-co — APPROVED** [review]
Looks good to me! :sunglasses:

**Comment by john-co** [comment]
As a follow up, is it necessary to have a single line for `var key_class = ${key_class};`? I feel like this can be removed since it's already set within the following poshi functions/macros.

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
