### PR TITLE
LPS-168067 HR_221 SR is not announcing "Open Graph Image" Dialog box

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://issues.liferay.com/browse/LPS-168067 

This is a sev2 but reopened by the client. What I get from the comments in the issue is that the speech history is correct, even if it is large, but that the modal title should match with the trigger button label. 

So here is the fix, I would appreciate your opinion about if this is enough for the issue. 

Screenshot 2023-06-09 at 11 42 21

cc/ @marcoscv-work

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Review by ethib137 — APPROVED** [review]
LGTM! Thanks @ambrinchaudhary

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by Jeremy-Ch** [comment]
ci:stop

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
LGTM!!! thanks @ambrinchaudhary !

**Comment by Jeremy-Ch** [comment]
Close this PR and send it from Lima, Thanks!

**Comment by Jeremy-Ch** [comment]
ci:close

**Comment by Jeremy-Ch** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/4381

**Pull request closed without merging**
